### ISSUE TITLE
App is stuck when capturing all webviews

### ISSUE THREAD

**Issue by omares** [responsively-org/responsively-app#1003]
# 🐞 bug report

### ✍️ Description

When using the "Screenshot All Webviews" feature on a mac and having a device with a `/` in its name added to the current suite, responsively does not close the "Capturing screen..." overlay, rendering it unusable.

### 🕵🏼‍♂️ Is this a regression?

No

### 🔬 Minimal Reproduction

Add a device with a `/` in its name to the current active suite.

### 🌍 Your Environment

<pre><code>Version: 1.5.0
Electron: 25.2.0
Chrome: 114.0.5735.134
Node.js: 18.15.0
V8: 11.4.183.23-electron.0
OS: Darwin arm64 22.5.0
</code></pre>

### 🔥 Exception or Error or Screenshot

![image](https://github.com/responsively-org/responsively-app/assets/1375307/4ec53003-b84f-4862-8d8b-4c5a8613841a)

**Comment by manojVivek** [comment]
This happens because the `/` is considered as a directory in the filesystem while writing the screenshot file, and it fails because we don't have that directory structure available. 

The fix is to replace the special characters in the device name with `-`.

**Comment by ThomasHoooo** [comment]
Hi @manojVivek, I would like to work on this issue :)

**Comment by itsajay1029** [comment]
Can you assign this issue to me and explain on what needs to be done ? @manojVivek

**Comment by manojVivek** [comment]
@ThomasHoooo go ahead, since you're here first. 😀
