### ISSUE TITLE
Wrong viewport size for S21 FE

### ISSUE THREAD

**Issue by Sutar210599** [responsively-org/responsively-app#1017]
# 🐞 bug report

### ✍️ Description

The application displays the screen size of s21 FE(1080 x 2340) instead of viewport size(~ 360 x 800). 
### 🔬 Minimal Reproduction

1. Add S21 FE to default or custom suite
2. On the main page, you'll find a browser window with wrong viewport size
### 🌍 Your Environment

<pre><code>
Version: 1.6.0
Electron: 25.2.0
Chrome: 114.0.5735.134
Node.js: 18.15.0
V8: 11.4.183.23-electron.0
OS: Windows_NT x64 10.0.19045
</code></pre>

### 🔥 Exception or Error or Screenshot
![image](https://github.com/responsively-org/responsively-app/assets/16016936/8ba81bf8-e573-426c-a7b6-bdc6a6e3eef2)

<pre><code>

</code></pre>

**Comment by ReshadSadik** [comment]
@manojVivek  can I work on this ?

**Comment by manojVivek** [comment]
@ReshadSadik Please go ahead! ❤️
