### ISSUE TITLE
Developer tools unable to dock again after un-dokcing

### ISSUE THREAD

**Issue by mvaneijgen** [responsively-org/responsively-app#1023]
# 🐞 bug report

### ✍️ Description

![Screenshot 2023-07-19 at 13 21 10 2](https://github.com/responsively-org/responsively-app/assets/3217544/1704cfdc-e7fb-4de0-8816-e57c64ceb2a9)

By mistake I've click the undock button for the developer tools an now it is a separate window and the buttons to re-dock it again are missing. I've also tried the "run command" in the developer tools menu with the following commands, but these do nothing. 

Dock to bottom
Dock to left
Dock to right
Restore last dock position

Screenshot from Chrome with the buttons that are missing responsively 

![Screenshot 2023-07-19 at 13 27 29](https://github.com/responsively-org/responsively-app/assets/3217544/64b37752-664c-4441-8d94-2aad67caf483)

### 🔬 Minimal Reproduction

Undock the DevTools and try re-docking again. 

### 🌍 Your Environment

<pre><code>
Version: 1.6.0
Electron: 25.2.0
Chrome: 114.0.5735.134
Node.js: 18.15.0
V8: 11.4.183.23-electron.0
OS: Darwin arm64 22.5.0
</code></pre>

**Comment by manojVivek** [comment]
To dock the DevTools back, you have to use the "Dock devtools" option in the menu as shown below.

<img width="368" alt="Screenshot 2023-07-19 at 6 11 26 PM" src="https://github.com/responsively-org/responsively-app/assets/1283424/3d453530-0595-47ab-9466-b9fa20e54ce7">

**Comment by mvaneijgen** [comment]
Welp, I was looking for the same buttons as in Chrome. Didn't see this toggle. My bad.
