### ISSUE TITLE
Developer tools stay white 

### ISSUE THREAD

**Issue by mvaneijgen** [responsively-org/responsively-app#1024]
# 🐞 bug report

### ✍️ Description

It seems like if a page refreshes and you try to inspect another device element it will 'crashes' and the DevTools stay white. It seems only to happen when the DevTools are 'docked'

![Screenshot 2023-07-19 at 13 21 10](https://github.com/responsively-org/responsively-app/assets/3217544/0e0fe8e3-be26-4fea-8b43-135ba1bd197e)

### 🔬 Minimal Reproduction

Have a page with the following meta tag `<meta http-equiv="refresh" content="5">`, have the DevTools open and try to inspect a new element when the page has refreshed. 

### 🌍 Your Environment

<pre><code>
Version: 1.6.0
Electron: 25.2.0
Chrome: 114.0.5735.134
Node.js: 18.15.0
V8: 11.4.183.23-electron.0
OS: Darwin arm64 22.5.0
</code></pre>

**Comment by Rajrits** [comment]
Could you please explain the issue more?? 
I could not find your mentioned issue.

**Comment by Rajrits** [comment]
Alright, I am new to open source please let me know if you have some good first issues for me.
I will be glad to work with you...
