### ISSUE TITLE
Rendering issue on linux

### ISSUE THREAD

**Issue by jwdotpark** [responsively-org/responsively-app#1030]
# 🐞 bug report

### ✍️ Description

Hi, thank you for the great product. I have a bug that rendering is broken completely on 1.6.0 and can't interact with any element.

### 🕵🏼‍♂️ Is this a regression?

It used to work fine prior to 1.6.0 afaik.

### 🔬 Minimal Reproduction

On initial render, graphical glitch happens automatically without any action. I'm using the latest mesa driver/kernel on Fedora linux and installed the app via AppImage.

### 🌍 Your Environment

<pre><code>
Linux Fedora 6.3.12 
Gnome 44.2
client glx vendor string: Mesa Project and SGI
OpenGL core profile version string: 4.6 (Core Profile) Mesa 23.1.3
OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.1.3
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 23.1.3
</code></pre>

### 🔥 Exception or Error or Screenshot
![Screenshot from 2023-07-24 14-01-23](https://github.com/responsively-org/responsively-app/assets/38537908/14aede5f-70d2-4545-bc35-3096844a0145)

![Screenshot from 2023-07-24 14-10-14](https://github.com/responsively-org/responsively-app/assets/38537908/e77053f7-99b3-4f9d-84a9-4dfa4110da93)

I can't be sure but it seems like the electron graphical dependency issue. Any other electron app runs fine except Responsively if it's worth it. Any help would be very appreciated.. thank you!

**Comment by manojVivek** [comment]
Strange, it must be something to do with the electron version, we'll give a try upgrading it in the next release.

**Comment by jwdotpark** [comment]
Hi, latest mesa driver fixed the issue, it wasn't on the app but on user end. Now it works perfectly fine. I'm gonna close the issue, sorry about this one!
