### ISSUE TITLE
Add support for gap css property

### ISSUE THREAD

**Issue by ollebergkvist** [responsively-org/responsively-app#1037]
# 🐞 bug report

### ✍️ Description

CSS property gap is not reflected in app.

https://developer.mozilla.org/en-US/docs/Web/CSS/gap

### 🔬 Minimal Reproduction

Try to use gap in any flex or grid container.

### 🌍 Your Environment

<pre><code>

</code></pre>

### 🔥 Exception or Error or Screenshot

<pre><code>

</code></pre>

**Comment by manojVivek** [comment]
@ollebergkvist You must be using an outdated version of the app v0.x. Please update to the latest and it should work: https://responsively.app/download
