### ISSUE TITLE
App gets stuck when taking full page screenshot

### ISSUE THREAD

**Issue by gomorizsolt** [responsively-org/responsively-app#1050]
# 🐞 bug report

### ✍️ Description

Related issue: https://github.com/responsively-org/responsively-app/issues/1003

When taking full page screenshots of all/individual devices, the app gets stuck. Quick screenshot is not working either.

### 🕵🏼‍♂️ Is this a regression?

Could be, because the bug started to appear right after upgrading to the latest version (`v1.7.0`).

### 🔬 Minimal Reproduction

Add any device to the suite and press "Screenshot All WebViews" / "Full Page Screenshot" / "Quick Screenshot".

### 🌍 Your Environment

<pre><code>
Version: 1.7.0
Electron: 25.2.0
Chrome: 114.0.5735.134
Node.js: 18.15.0
V8: 11.4.183.23-electron.0
OS: Darwin arm64 22.5.0
</code></pre>

### 🔥 Exception or Error or Screenshot

![responsively_bug](https://github.com/responsively-org/responsively-app/assets/30864202/981d564b-18f9-4757-b3c6-41da4c7de1c9)

**Comment by rei2232** [comment]
https://github.com/responsively-org/responsively-app/pull/1055

**Comment by gomorizsolt** [comment]
@manojVivek I am still experiencing the same behaviour, after updating to the latest version.
