### ISSUE TITLE
Refresh a single view

### ISSUE THREAD

**Issue by basilbabaa** [responsively-org/responsively-app#1064]
# 🚀 Feature Request

### 📝 Description

 I still need to be able to refresh a single view at a time without having to open the console to do so.

### ✨ Describe the solution you'd like

A button on each view window, beside the rotate button, that refreshes JUST that view.

### ✍️ Describe alternatives you've considered

I'm currently using another tool until this feature gets added to Responsively.  I check periodically to see, and I have asked for it before, but it has yet to be added.

**Comment by ParamBirje** [comment]
Hey @manojVivek @basilbabaa , here's a quick mock-up of how the solution would look like.

![refresh-single-view-responsively](https://github.com/responsively-org/responsively-app/assets/87022870/4a63a78c-c4b7-4941-8364-04aa30c86f58)

Is this how it should be implemented? Please let me know if there should be any specifics covered, and I'll try having them covered.

**Comment by manojVivek** [comment]
@ParamBirje This looks good, but personally, I would like to have the refresh button as the first option in the toolbar.
