### ISSUE TITLE
[Question] How are DPI calculated for devices?

### ISSUE THREAD

**Issue by bySabi** [responsively-org/responsively-app#1087]
How do you calculate the dpi you have in the list of devices?

If I want to add, for example, a "Galaxy Note 10" _412x869_ device as a DPI calculation?

Good job with this app. saved my day

**Comment by mohitthakur9901** [comment]
DPI (width) = 412 pixels / 2.83 inches ≈ 145.33 DPI
You can perform a similar calculation for the height.
the actual physical screen size may vary slightly based on the device model, so it's essential to obtain accurate measurements for precise DPI calculations.

**Comment by bySabi** [comment]
thanks @mohitthakur9901
