### ISSUE TITLE
App wont start after update.

### ISSUE THREAD

**Issue by KevinBeckers** [responsively-org/responsively-app#1097]
# 🐞 bug report
App wont start after update.

### ✍️ Description

App wont start after update.

### 🔬 Minimal Reproduction

Download version 1.8.0 and launch.

### 🌍 Your Environment

<pre><code>
- M1 Max
- Ventura 13.5.1
</code></pre>

### 🔥 Exception or Error or Screenshot

<pre><code>
./ResponsivelyApp
(node:6206) ExtensionLoadWarning: Warnings loading extension at /Users/kevin/Library/Application Support/ResponsivelyApp/extensions/fmkadmapgofadopljbjfkapdkoienihi:
  Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

(Use `ResponsivelyApp --trace-warnings ...` to show where the warning was created)
(node:6206) ExtensionLoadWarning: Warnings loading extension at /Users/kevin/Library/Application Support/ResponsivelyApp/extensions/lmhkpmbekcpmknklioeibfkpmmfibljd:
  Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
  Permission 'notifications' is unknown or URL pattern is malformed.
  Permission 'contextMenus' is unknown or URL pattern is malformed.

(node:6206) ExtensionLoadWarning: Warnings loading extension at /Users/kevin/Library/Application Support/ResponsivelyApp/extensions/bmdblncegkenkacieihfhpjfppoconhi:
  Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
  Permission 'contextMenus' is unknown or URL pattern is malformed.

(node:6206) ExtensionLoadWarning: Warnings loading extension at /Users/kevin/Library/Application Support/ResponsivelyApp/extensions/bhljhndlimiafopmmhjlgfpnnchjjbhd:
  Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

(node:6206) ExtensionLoadWarning: Warnings loading extension at /Users/kevin/Library/Application Support/ResponsivelyApp/extensions/dbhhnnnpaeobfddmlalhnehgclcmjimi:
  Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
  Cannot load extension with file or directory name Thumbs.db. The filename is illegal.

(node:6206) ExtensionLoadWarning: Warnings loading extension at /Users/kevin/Library/Application Support/ResponsivelyApp/extensions/ienfalfjdbdpebioblfackkekamfmbnh:
  Permission 'scripting' is unknown or URL pattern is malformed.

(node:6206) ExtensionLoadWarning: Warnings loading extension at /Users/kevin/Library/Application Support/ResponsivelyApp/extensions/nhdogjmejiglipccpnnnanhbledajbpd:
  Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

(node:6206) ExtensionLoadWarning: Warnings loading extension at /Users/kevin/Library/Application Support/ResponsivelyApp/extensions/pfgnfdagidkfgccljigdamigbcnndkod:
  Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
  Permission 'contextMenus' is unknown or URL pattern is malformed.

(node:6206) ExtensionLoadWarning: Warnings loading extension at /Users/kevin/Library/Application Support/ResponsivelyApp/extensions/jdkknkkbebbapilgoeccciglkfbmbnfm:
  Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

09:48:56.870 › Checking for update
(node:6206) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND localhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26)
(node:6206) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
</code></pre>

**Comment by manojVivek** [comment]
It looks like the app cannot resolve `localhost` on your machine, you probably have some network config changing that behaviour? 

The app loads the UI files using localhost, so this is preventing the app from loading the files, causing the crash.

**Comment by KevinBeckers** [comment]
Thank you, I added localhost to my Hostfile and now the app starts again.
