### ISSUE TITLE
Screenshot location input remains white in dark mode In Settings

### ISSUE THREAD

**Issue by NishidhJain** [responsively-org/responsively-app#1111]
# 🐞 bug report

### ✍️ Description
The input for screenshot save location should turn into dark if the UI theme is changed to dark mode but the input remains in light mode and text inside it is hard to read. So changing it into dark mode will fix this issue. Also the width of the settings dialog is way bigger which looks bad on large screens so adding a max-width can resolve this.

### 🔬 Minimal Reproduction

1. Turn the UI Theme to dark mode
2. Go to Settings and a dialog will open

![image](https://github.com/responsively-org/responsively-app/assets/61869195/bd82f4af-3648-44d3-bbb0-f2b4e604294a)

### 🌍 Your Environment

MacOS -  ResponsivelyApp - Version 1.8.0 (1.8.0)

### 🔥 Expectation 

![image](https://github.com/responsively-org/responsively-app/assets/61869195/af81b798-54ff-4f8b-97ce-6ab8390f69ad)

Please assign this issue to me, I would be happy to work on it

Thank You,
Nishidh Jain

**Comment by Alok-Singh-ops** [comment]
@manojVivek i want to work on this issue. Please assign it to me
