### ISSUE TITLE
ERROR: -202, ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by do-kevin** [responsively-org/responsively-app#1142]
Hey folks,

I am testing a staging website at my company where it would pop up a modal that asks for login credentials upon first load. However, it's not secured and doesn't have a valid certificate. Therefore, Error "-202" appears. How do I bypass it on Responsively App? On Chrome, I would just click on Advanced and accept to proceed to go to the URL.

**Comment by manojVivek** [comment]
Hey, the "Allow Insecure SSL" option here might help with this: <img width="357" alt="Screenshot 2023-10-27 at 9 13 21 PM" src="https://github.com/responsively-org/responsively-app/assets/1283424/4b242aab-e30a-4f04-8f3e-9e5f0b4e8ddb">

**Comment by do-kevin** [comment]
> Hey, the "Allow Insecure SSL" option here might help with this: <img alt="Screenshot 2023-10-27 at 9 13 21 PM" width="357" src="https://user-images.githubusercontent.com/1283424/278692926-4b242aab-e30a-4f04-8f3e-9e5f0b4e8ddb.png">

So with that option enabled, it is just stuck loading and never succeeds.

**Comment by manojVivek** [comment]
Can you check the devtools network tab to see what's happening? 

Also, it would be great to troubleshoot if you can share the url of the page you're trying to load.

**Comment by do-kevin** [comment]
> Can you check the devtools network tab to see what's happening? 
> 
> Also, it would be great to troubleshoot if you can share the url of the page you're trying to load. 

I'll check the network tab and see what I can report to you on Monday. The site I'm working with is from a company, so I cannot share it.

**Comment by do-kevin** [comment]
And I can confirm that it works on Sizzy browser. So I don't think it's the website. I'll send you what I see on the Network tab on Monday or later that week.

**Comment by do-kevin** [comment]
Sorry for such a late reply, but I tried it again today and it appears to be working. I'm also on Version 1.8.0. I don't know why I don't get the ERROR: -202, ERR_CERT_AUTHORITY_INVALID anymore.

Maybe something changed on the website from my company's side. I do not know.

Since I can't reproduce this error, I'll close the comment.
