### ISSUE TITLE
Multi-screenshot duplicates info on the largest screen

### ISSUE THREAD

**Issue by avimar** [responsively-org/responsively-app#117]
I'm not exactly sure what's going wrong, but I think there's an issue with syncing the scroll for full-page screenshots.

Here's with 4 portrait devices: iphone 6/7/8 plus, iphone x, ipad, laptop. Browsing https://www.freedomhot.com

The laptop one has duplicated parts of the screen (probably because it already reached the bottom of the page?)

[Localhost - iPad - 2020-25-5 at 9 55 05 PM](https://user-images.githubusercontent.com/314077/82837754-a4988080-9ed2-11ea-84e1-40a8a05b34be.png)
[Localhost - Laptop - 2020-25-5 at 9 55 05 PM](https://user-images.githubusercontent.com/314077/82837757-a95d3480-9ed2-11ea-8205-6f2e6bdcb014.png)

When I add a kindle fire hdx to the list (actually the "laptop" crashed during screenshot. But closing it and relaunching)... the kindle fire hdx is now OK, but both the ipad and laptop are messed up.

[Freedomhot - Laptop - 2020-25-5 at 9 59 28 PM](https://user-images.githubusercontent.com/314077/82837875-1bce1480-9ed3-11ea-975b-db1ea11ab44b.png)
[Freedomhot - iPad - 2020-25-5 at 9 59 28 PM](https://user-images.githubusercontent.com/314077/82837876-1cff4180-9ed3-11ea-9b68-e59864f62a69.png)
[Freedomhot - Kindle Fire HDX - 2020-25-5 at 9 59 28 PM](https://user-images.githubusercontent.com/314077/82837878-1e306e80-9ed3-11ea-956a-132fe0d3bb28.png)

I made sure I started the scrolls all the way on top, no funny interactions to change the state.

**Comment by manojVivek** [comment]
@avimar This issue is fixed in version v0.12.0 of the app. Please upgrade the app and check it out. 
Closing the issue for now, feel free to re-open it if you still face any problems.

**Comment by avimar** [comment]
On the latest auto-update, full screenshots (either on one viewport or all) just hangs.
version 0.12.0
