### ISSUE TITLE
@media screen and (min-width:320px){ 

### ISSUE THREAD

**Issue by brohrer68** [responsively-org/responsively-app#1172]
# 🐞 bug report

### 🌍 Your Environment

<pre><code>

</code></pre>

### 🔥 Exception or Error or Screenshot

<pre><code>

</code></pre>

**Comment by brohrer68** [comment]
the min and max-width css for screen size 320px does not seem to be working. it does on a range of 321-360px

**Comment by Asin-Junior-Honore** [comment]
@brohrer68  I would love to work on this

**Comment by brohrer68** [comment]
Hello Asin-Honore, 

What exactly would you like of work on, and do you know MySQL Databasing? 

––––––––––––––––––––––––––––
BRYAN KEITH ROHRER 
––––––––––––––––––––––––––––
Branding | Content Writing | Graphic & Logo Design | Internet Marketing 
Marketing Campaigns | Photography | Promotional Products | Social Media Management 
Video Directing, Editing, & Production | Website Design & Development
––––––––––––––––––––––––––––
Mobile: 720-645-3516 | Email: ***@***.***
Location: Aurora, Colorado | Web: https://www.bryankeithrohrer.com 
––––––––––––––––––––––––––––
CONFIDENTIALITY  STATEMENT
This email and any attachments from Bryan Keith Rohrer, is confidential and intended solely for the use of the individual or entity to which it is addressed.  The information contained herein may include protected or otherwise privileged information. If you are not the intended audience addressed, you are unauthorized review, forwarding, print, copy, distribute, or use such information. The information is strictly prohibited and may be unlawful.  If you have received this message in error, please notify the sender by reply to this message and delete the email without further disclosure.
––––––––––––––––––––––––––––

**Comment by violetadev** [comment]
Closing this since there is no context, nor explanation
