### ISSUE TITLE
Hot reload forces app to become front window

### ISSUE THREAD

**Issue by greatwitenorth** [responsively-org/responsively-app#1184]
# 🐞 bug report

### ✍️ Description

Given that I have a hot reloadable page loaded in the Responsively App, and the app is not currently the front window, when the page hot reloads, the Responsively app automatically becomes the front window, disrupting my work.

### 🕵🏼‍♂️ Is this a regression?

Unsure

### 🔬 Minimal Reproduction

- Load a hot reloadable page in Responsively
- Open your code editing program to the site that's currently loaded
- Make an edit in your code and save
- The Responsively app will automatically become the front window 

### 🌍 Your Environment

<pre><code>
Version: 1.10.0
Electron: 27.0.4
Chrome: 118.0.5993.129
Node.js: 18.17.1
V8: 11.8.172.17-electron.0
OS: Darwin arm64 23.1.0
</code></pre>

**Comment by preeteshjain** [comment]
Happening with me as well. Really annoying behaviour. How can we fix this?

**Comment by preeteshjain** [comment]
Happening with me as well. Really annoying behaviour. How can we fix this?

Possible duplicate https://github.com/responsively-org/responsively-app/issues/837

**Comment by jkaeske** [comment]
Same here

**Comment by preeteshjain** [comment]
I think this is the code that is causing the issue:

https://github.com/responsively-org/responsively-app/blob/e32d1c309ac2e40e102887d800010728eab7d84b/desktop-app/src/main/main.ts#L200-L209

**Comment by PH7-Jack** [comment]
Same issue on macOS Sonoma

**Comment by ropdias** [comment]
Same here, I agree with @preeteshjain that it's a very annoying behaviour. I'm using VSCode with Live Server. Every time I change code Responsively App get focus an open again. There should be a way to remove this behaviour in the Settings.

**Comment by jb-dev1** [comment]
Same issue with MacOS Sonoma 14.5, default production download from https://responsively.app (v1.12.0, Apple Silicon) and VS Code v1.91.1 with Auto Save /afterdelay enabled.

**Comment by violetadev** [comment]
hi there, I have opened a PR to fix this. The problem was the app kept being "ready" whenever hot reloading was triggered, making it initiate again and again, and bringing it to the front. I have added a simple fix and it looks like it's working well.
