### ISSUE TITLE
Add ctrl key icons in shortcuts window

### ISSUE THREAD

**Issue by johnt1838** [responsively-org/responsively-app#1185]
In the window that displays the shortcuts, mac keys appear even windows machines. Please add CTRL (if ctrl is used) key icons when the app is running from a windows (or linux) machine and not mac.

![2024_01_19_05_33_17_Window](https://github.com/responsively-org/responsively-app/assets/45724158/e4b9a420-2dd2-4145-b6d5-6e96b312afc3)

**Comment by 2div** [comment]
Hi @manojVivek  I would like to handle this task. if no one handling it , kindly assign to my name.
I would appreciate , if give me some guide on how to start to solve this issue.
Thank you

**Comment by ketansahugit** [comment]
Will start working on this right away.

**Comment by 123upasana** [comment]
Hi @manojVivek, I would like to work on this issue. Please assign it to me.
