### ISSUE TITLE
When rotating to landscape, update the aspect ratio of the location on the main screen for some phone targets

### ISSUE THREAD

**Issue by JeroenHeemskerk** [responsively-org/responsively-app#1210]
# 🚀 Feature Request

### 📝 Description

When Rotating a iphone 12 in the main window to landscape mode, the width on screen stays the same and a the screen is not shown entirely.
 
### ✨ Describe the solution you'd like
When Rotating any device (or all devices) in the main window to landscape mode, the width on screen should be adjusted to reflect the new aspect ratios (possible as an opt-in option)

### ✍️ Describe alternatives you've considered

It works for ipad and macbook and also if I look at the iphone device indiviually the aspect ratio is correct

**Comment by JeroenHeemskerk** [comment]
![Responsivly Portait](https://github.com/responsively-org/responsively-app/assets/41477180/38122b9a-32c8-4fa6-9241-dcaea2f4ab6a)
All Portrait mode
![Responsivly Landscape](https://github.com/responsively-org/responsively-app/assets/41477180/54096b60-167f-4ca6-a552-ba5f119f7c95)
Current All Landscape mode
![Responsivly Landscape new layout](https://github.com/responsively-org/responsively-app/assets/41477180/92944afb-a0d0-43ad-adf0-48a2ead28b06)
Expected All Landscape mode

**Comment by happymvp** [comment]
I'll take this one
