### ISSUE TITLE
Unified dev tool not showing up

### ISSUE THREAD

**Issue by SolberLight** [responsively-org/responsively-app#1223]
# 🐞 bug report

### ✍️ Description

CHTRL + SHIFT + I isn't opening unified dev tools

### 🕵🏼‍♂️ Is this a regression?

Yes?

### 🔬 Minimal Reproduction

CTRL + SHIFT + I when app open

### 🌍 Your Environment

  -> not working

W11
Last version of the app

### 🔥 Exception or Error or Screenshot
/

**Comment by manojVivek** [comment]
@SolberLight I just checked and the correct shortcut for unified dev tools is `Ctrl` + `i` and it works for me. 

Can you please try that?

**Comment by SolberLight** [comment]
> @SolberLight I just checked and the correct shortcut for unified dev tools is `Ctrl` + `i` and it works for me. 
> 
> Can you please try that? 

Just tried. Still not working for me

**Comment by eriickz** [comment]
> Just tried. Still not working for me

Using `Ctrl` + `i` you toggle on/off the inspect mode and when you click on any element of any device in the previewer, the devtools opens automatically.

There is no shortcut to open/hide devtools.
