### ISSUE TITLE
Add "ScrollToTop" Button for User Enhancement

### ISSUE THREAD

**Issue by codercake** [responsively-org/responsively-app#1234]
# 🚀 Feature Request

### 📝 Description

Currently, the application lacks a convenient way for users to quickly navigate back to the top of the page, especially when browsing through lengthy content. Implementing a "Scroll to Top" button would greatly enhance user experience by providing a simple and efficient means to return to the top of the page with just one click.

### ✨ Describe the solution you'd like

- Add a small, unobtrusive button at the bottom-right corner of the screen that becomes visible as the user scrolls down the page.
- When clicked, the button smoothly scrolls the page back to the top.
- Ensure the button remains responsive and accessible across different screen sizes and devices.

### ✍️ Describe alternatives you've considered

One alternative could be implementing a keyboard shortcut for scrolling to the top, but this may not be as intuitive or accessible to all users compared to a visible button. Some browsers already have a built-in "scroll to top" functionality when users click on the browser's scrollbar, but having a dedicated button within the application would provide a consistent experience across different platforms.

**Comment by Shashan17J** [comment]
Hi, I would like to work on this issue. Could you please assign it to me?

**Comment by manojVivek** [comment]
@Shashan17J Please proceed with the implementation, we don't assign issues.
