### ISSUE TITLE
Error installing app on Windows 11: direct access not found

### ISSUE THREAD

**Issue by Soujiro17** [responsively-org/responsively-app#1236]
# 🐞 bug report

### ✍️ Description

Hi there! there's no much info about this error, but when i download the windows installer and initialized the installation, after around 2 seconds the install finalized and shows a windows emergent window that is looking for the direct access of app. When you click "repair button", it doesn't work, and still not working.

### 🕵🏼‍♂️ Is this a regression?

I don't know.

### 🔬 Minimal Reproduction

Download windows installer, execute it, and that's it.

### 🌍 Your Environment

My SO is Windows 11 Home Single Language V.23H2. My hardware spects are this:

* AMD Ryzen 7 6800H with Radeon Graphics 3.2 GHz
* RAM 32GB DDR5 4800 MHz
* GPU RTX 3070 Ti
* Micron 3400 NVMe™ SSD

### 🔥 Exception or Error or Screenshot

![image](https://github.com/responsively-org/responsively-app/assets/13888213/371403c7-aa4b-4463-9e9a-f40922db8be0)
![image](https://github.com/responsively-org/responsively-app/assets/13888213/fcd77cd3-966b-4211-8a3d-29a558d5e2c0)

Thank you!

**Comment by pezexd** [comment]
Same error

**Comment by manojVivek** [comment]
Sorry, I don't have an existing setup of windows. But when I tried on a fresh machine, the installation worked fine. 

Can you try uninstalling the app and then re-installing it? 

I don't have a dedicated Windows machine and trying it only on a cloud instance, so need help figuring out what is wrong on your setup.

**Comment by Soujiro17** [comment]
> Sorry, I don't have an existing setup of windows. But when I tried on a fresh machine, the installation worked fine.
> 
> Can you try uninstalling the app and then re-installing it?
> 
> I don't have a dedicated Windows machine and trying it only on a cloud instance, so need help figuring out what is wrong on your setup.

Hi Manoj, i tried reinstalling the app at least 3 times and still not working.

**Comment by manojVivek** [comment]
@Soujiro17 Thanks for confirming. 
Is there any specific error that you're facing? Also, is the problem during the installation or while opening the app?

**Comment by khusantoy** [comment]
I have a problem like this How can I fix it? Help me

**Comment by manojVivek** [comment]
@Soujiro17 @pezexd @khusantoy I just published a new version of the app with some fixes, can you please try it and let me know if that works for you? https://responsively.app/download

**Comment by Soujiro17** [comment]
@manojVivek now it works, i was able to install the app. thank you!!

**Comment by khusantoy** [comment]
> @Soujiro17 @pezexd @khusantoy I just published a new version of the app with some fixes, can you please try it and let me know if that works for you? https://responsively.app/download

Thanks, It works
