### ISSUE TITLE
Create suite device screens based on design tokens

### ISSUE THREAD

**Issue by nicolasperez19** [responsively-org/responsively-app#1240]
# 🚀 Feature Request

### 📝 Description

Responsively allows you to create and manage suites for different device and screen sizes. The issue is that you have to manually set the suites yourself and if you're working with a team this could easily get out of sync, especially if your team is using a design system with design tokens.

### ✨ Describe the solution you'd like

It would be nice if in the settings you can select a file directory or URL with a design token spec and automatically generate the screen sizes based on the design token spec.

**Comment by Honeylabh** [comment]
Proposed Solution
It would be highly beneficial to have a feature in the settings that allows users to select a file directory or URL containing a design token spec. Responsively could then automatically generate the screen sizes based on the design token spec. This would ensure consistency across the team and streamline the setup process.

Benefits
Consistency: Ensures all team members are using the same screen sizes.
Efficiency: Saves time by automating the setup process.
Integration: Seamlessly integrates with design systems and design tokens, aligning with industry best practices.
Example Workflow
In the settings, provide an option to input a file path or URL pointing to the design token spec.
Responsively parses the design token spec to extract screen size information.
Automatically generate and update the screen size suites based on the extracted data.
Additional Considerations
Support for common design token formats (e.g., JSON, YAML).
Ability to manually override automatically generated screen sizes if needed.
Periodic sync option to update screen sizes when the design token spec changes.

**Comment by violetadev** [comment]
@nicolasperez19 @Honeylabh please note that now you can export and import suites and custom devices. So you would only have to set it up once, then export it and share it with your team
