### ISSUE TITLE
"Device DPI" is actually Device Pixel Ratio (DPR) and should allow decimals

### ISSUE THREAD

**Issue by kkmuffme** [responsively-org/responsively-app#1257]
# 🐞 bug report

### ✍️ Description

"Device Manager" - the "Device DPI" isn't actually "DPI" but "DPR" (Device Pixel Ratio)
How I know? The values used in the presets (1 and 2) would mean a screen is unusable since the resolution is so low. Common values for DPI are much higher, in the 70+ range.
Please rename this.

Additionally, it should allow decimals, since a DPR of 1.5 is rather common too and often behaves differently than 2.

### 🕵🏼‍♂️ Is this a regression?

No

### 🌍 Your Environment

1.12.0

**Comment by wp043** [comment]
Can I work on this?
