### ISSUE TITLE
Export/import option missing again in 1.12.0

### ISSUE THREAD

**Issue by kkmuffme** [responsively-org/responsively-app#1258]
# 🐞 bug report

### ✍️ Description

Export/import doesn't exist anymore in 1.12.0
Was implemented in https://github.com/responsively-org/responsively-app/pull/657

### 🕵🏼‍♂️ Is this a regression?

Yes

### 🌍 Your Environment

1.12.0

**Comment by artnerdnet** [comment]
is this a good first issue? can I take this?

**Comment by manojVivek** [comment]
Yes, please go ahead and let me know if you have any questions.

**Comment by violetadev** [comment]
I see that all this is in the legacy code, so we must migrate it to the new app. I will add it in the settings, on top of the SAVE button:

![image](https://github.com/user-attachments/assets/48dd9c87-6e38-48c0-8fa4-652e2ecf1da7)

**Comment by manojVivek** [comment]
Yes, that sounds perfect!
