### ISSUE TITLE
Responsively shows a site with no view port as responsive on mobile when other emulators and real mobile devices show the issue

### ISSUE THREAD

**Issue by chivandikwa** [responsively-org/responsively-app#1267]
# 🐞 bug report

### ✍️ Description

Responsively shows a site with no view port as responsive on mobile when other emulators and real mobile devices show the issue.

Notice how this looks with the edge emulator (this is also how it looks on a real device)

![image](https://github.com/user-attachments/assets/64ea97cc-b93c-454b-a8fc-bb8d3f16c7d8)

Notice how it looks OK in Responsively
![image](https://github.com/user-attachments/assets/8acf6499-6307-4c62-b649-2ff7e46a06fa)

### 🕵🏼‍♂️ Is this a regression?

First time user

### 🔬 Minimal Reproduction

Open the page https://www.w3schools.com/html/example_withoutviewport.htm

### 🌍 Your Environment

Windows 11 machine.

**Comment by violetadev** [comment]
hi @chivandikwa ! I took a look, and it seems that you are missing the correct meta tag in your file, in order for the browser to work with the responsiveness of your page properly. [Here's some info on that](https://www.w3schools.com/css/css_rwd_viewport.asp#:~:text=%3Cmeta%20name%3D%22viewport%22,the%20page's%20dimensions%20and%20scaling.) 
I also recommend you always wrap your code inside a parent div, the correct code would look like this:

```
<!DOCTYPE html>
<html>
   <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
   </head>
   <body cz-shortcut-listen="true">
      <div>
         <p><b>To understand this example, you should open this page on a phone or a tablet.</b></p>
         <img src="./example_withoutviewport_files/img_chania.jpg" alt="Chania" width="460" height="345">
         <p>
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
            Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum.
            Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum.
         </p>
      </div>
   </body>
</html>
```

**Comment by manojVivek** [comment]
Based on @violetadev's details explanation of this on the [Discord thread](https://discord.com/channels/992277343408246825/992277476564815952/1268463220260208660) (quoted below), this is not an issue. Missing `viewport` meta tag doesn't mean it'll be rendered the same in all browser engines. 

> it's that the viewport behaviour of responsively app is different from the browsers where the page was tested, and since it didn't have the meta tag, it rendered differently, adjusting the pixel sizing (which is normal, you can't assure same rendering across devices without the meta tag). If you add the meta tag to his code, it renders the same in browser, mobile and in the responsively app

Please reopen this, if you have any specific question on this.
