### ISSUE TITLE
Enhance Search Bar Behavior to Select Entire URL on Click

### ISSUE THREAD

**Issue by naeem4633** [responsively-org/responsively-app#1272]
### Problem

The current behavior of the search bar in the Responsively App only places the cursor at the clicked position instead of selecting the entire URL. This differs from the standard browser behavior, where clicking the address bar selects the entire URL, allowing for quick replacement.

### Proposed Solution

Update the search bar interaction to select the entire URL when clicked, similar to web browsers like Chrome and Firefox.

### Benefits

- **Aligns the app's behavior with common browser practices**, enhancing user experience.
- **Allows users to quickly replace URLs** without manually selecting the text.
- **Provides a more intuitive interaction** for frequent testers of URLs.

## Steps to Reproduce

1. Open the Responsively App.
2. Navigate to any URL.
3. Click on the search bar.
4. Notice that the entire URL is not selected; only the cursor appears.

## Additional Context

This feature will improve usability for users who frequently switch between the app and web browsers, offering a consistent experience.

## Screenshots/GIFs

![gif 1](https://github.com/user-attachments/assets/132640a6-8aef-4a85-b9bf-6b2bd4cdf88e)

**Comment by keshav-maheshwari707** [comment]
In my system, it is selecting the whole URL

**Comment by naeem4633** [comment]
On my side it does not select the whole thing, I'm on a windows PC.

**Comment by Pulkitxm** [comment]
I want to work on this issue

**Comment by manojVivek** [comment]
Fixed in https://github.com/responsively-org/responsively-app/pull/1275
