### ISSUE TITLE
Updating or Removing URL Query Params not updating the page 

### ISSUE THREAD

**Issue by joshuacue** [responsively-org/responsively-app#1273]
# 🐞 bug report
URL/URL Query not updating

### ✍️ Description
Page doesn't update when you manuall change/remove query URL params.

### 🔬 Minimal Reproduction
-Go to -- >` localhost:4000/xxxx-xx?queryKey=query-value`
-Manually change `localhost:4000/xxxx-xx` to see variant of the page without queryKey
-It will suggest the `localhost:4000/xxxx-xx?queryKey=query-value`, ignore it by either pressing Escape or click outside so suggestion disappears
-URL will change to the `localhost:4000/xxxx-xx` but page won't rerender/update to the variant without the URL query params so you will assume you need to reopen the app
-Reopen the app, enter the `localhost:4000/xxxx-xx` again and ignore the suggestion 
-Press Enter and you will be redirected to` localhost:4000/xxxx-xx?queryKey=query-value` 😆 

### 🌍 Your Environment

<pre><code>
MacOS Sonoma 14.3
Chrome Version 127.0.6533.89 (Official Build) (arm64)
NextJs 14 + nuqs -- could be helpful 
</code></pre>

### Clear History

**Comment by pradeepbgs** [comment]
looks interesting issue , let  me see and  test the issue

**Comment by pradeepbgs** [comment]
Hey can you share the video ? So it would be helpful for me to see the problem and contribute to it

**Comment by happymvp** [comment]
@pradeepbgs Any updates?

**Comment by mini96** [comment]
Hi, I was wondering if I can help solve this issue. I have free time laying around and wanted to contribute in any way shape or form.

**Comment by happymvp** [comment]
You can do it! I do something else. 
Also you can join discord chat, Contributors responding there quite often.

**Comment by mini96** [comment]
Thanks mate, joining the dc now. I will keep you in the loop of how I go, btw do I get assigned the task here or in dc

**Comment by happymvp** [comment]
I guess nowhere, by my experience. People will just see that you are doing it by reading thread.
I'm also new in this community, so don't get me wrong, I'm not source of truth, I just was last person in the task you wrote, so I respond to you =)

**Comment by mini96** [comment]
I see, well all is good. I will just start working on it now. Gonna have a field day trying to replicate the issue as I am on windows so wish me luck ahahahah

**Comment by mini96** [comment]
So I found a simple workaround until I fix this issue 

- Copy the desired URL in this case localhost:4000/xxxx-xx
- Go to a separate URL such as https://www.google.com/
- Then simply copy paste your desired URL then press enter

**Comment by mohamed1408** [comment]
Found the issue.

When hitting enter from the address box if you have suggestions you are sending the url from the active suggestions
`suggestions[activeIndex] != null
            ? suggestions[activeIndex].url`
but what you really need to do is to send the `typedAddress` to `dispatchAddress: (url?; string)`

**Comment by mohamed1408** [comment]
> So I found a simple workaround until I fix this issue
> 
> * Copy the desired URL in this case localhost:4000/xxxx-xx
> * Go to a separate URL such as https://www.google.com/
> * Then simply copy paste your desired URL then press enter

This is not appropriate fix.
Why

**Comment by mohamed1408** [comment]
I think I fixed some issues - if those weren't issues sorry to bother you.
1. While pressing escape the suggestions were not closing - not set to false.
2. Due to the above issue whenever we press `Enter` from the address bar the first or active suggestion's url get dispatched.
3. `Enter` key press is not handled from Address Bar

[commit#f305210](https://github.com/mohamed1408/responsively-app/commit/f305210d2270e71bcbeb86b1192afe8dbc698720)
