### ISSUE TITLE
Unable to edit information of custom device after duplicate name error

### ISSUE THREAD

**Issue by wp043** [responsively-org/responsively-app#1279]
# 🐞 bug report

### ✍️ Description
In device manager, when we hit the error of duplicate device name, after the pop up, none of the inputs can be modified, even if exiting the window and add again.

### 🕵🏼‍♂️ Is this a regression?
No

### 🔬 Minimal Reproduction
Create a custom device in device manager first. Then add another one that has the same name as the previous one. When click on "Add", the error pops up. After that, try selecting the fields and edit the names.

### 🌍 Your Environment
<pre><code>
App Version: 1.13.0
Electron Version: 27.0.4
Chrome Version: 118.0.5993.129
Node.js Version: 18.17.1
V8 Version: 11.8.172.17-electron.0
OS: Windows_NT x64 10.0.22631
</code></pre>

### 🔥 Exception or Error or Screenshot
![error](https://github.com/user-attachments/assets/2f2819cc-6c84-49df-b9ee-9c58cbe37a8a)

**Comment by pranavithape** [comment]
what you saying i can edit those values bro

**Comment by pranavithape** [comment]
Wait May Be You Are Right But Partially , Values editable with arrows but selection frozen

**Comment by pranavithape** [comment]
Yeh I confirmed there is error you cant select value and edit it freezes
