### ISSUE TITLE
FEAT:  To introduce toggling feature to switch from dark mode to light mode and vice versa

### ISSUE THREAD

**Issue by Lavavarshney** [responsively-org/responsively-app#1284]

**Comment by violetadev** [comment]
hi @Lavavarshney , we already have this feature, you can toggle the theme by clicking on the moon/sun:

<img width="380" alt="Screenshot 2024-08-10 at 11 21 35" src="https://github.com/user-attachments/assets/a09176c3-47fc-48c8-ac47-fc5c557c0cdf">

if this is not what you mean, please add more info to the issue. Thanks!

**Comment by teja-pola** [comment]
Well @violetadev please close this issue
