### ISSUE TITLE
Download for Windows button on website just keeps loading 

### ISSUE THREAD

**Issue by Yetunde495** [responsively-org/responsively-app#1294]
# 🐞 bug report

### ✍️ Description

When I click on the download for Windows button, I get redirected but the page just keeps loading

**Comment by teja-pola** [comment]
Check once, I think its working now

**Comment by violetadev** [comment]
hi @Yetunde495 , could you check again and make sure it's not your connection? It is working for me. You can also right click the button and press "copy link address", then paste it in a new tab. Let me know if you still have issues.

**Comment by violetadev** [comment]
I have merged a fix now, since we had more reports. Let me know if it happens again. Thanks
