### ISSUE TITLE
Link to roadmap doesnt work 

### ISSUE THREAD

**Issue by No898** [responsively-org/responsively-app#1302]
# 🐞 bug report
Link on github to road map doesnt work

### ✍️ Description
Link on github to read map link to 404

### 🕵🏼‍♂️ Is this a regression?
no

**Comment by QaisarMoin** [comment]
hello , can you provide some screenshot ?

**Comment by No898** [comment]
![image](https://github.com/user-attachments/assets/c2d17996-f436-44fc-8dda-947867c41fab)

https://github.com/responsively-org/responsively-app/projects/12?fullscreen=true

Hello, you can try it, it doesnt work.

**Comment by QaisarMoin** [comment]
It seems that there is no projectin the projects section
