### ISSUE TITLE
Sign the installer wit a certificate

### ISSUE THREAD

**Issue by k-risc** [responsively-org/responsively-app#1303]
As it seems, the installer for v1.14.0 is still not signed. This was reported in https://github.com/responsively-org/responsively-app/issues/96 a few times, maybe elsewhere as well.

**Comment by manojVivek** [comment]
@k-risc Thanks for raising this issue, but as mentioned in the thread. Windows signing certificates as too expensive, costing upwards of $300/year. So the Windows app will remain unsigned, until the signing certificate pricing situation improves. 

Closing this issue, please feel free to reopen if you have any specific questions, would be happy to answer them.
