### ISSUE TITLE
bug on opening not stay in the position/layout/monitor

### ISSUE THREAD

**Issue by Raxiel1987** [responsively-org/responsively-app#1316]
# 🐞 bug report

### ✍️ Description

when i open the program and put in on another monitor ( i have 2 monitor) on the next opening the program reopen on the wrong monitor, and don't remember the position in the monitor and not remember the window dimension but it always open in full screen

**Comment by SauravGupta123** [comment]
Can you share the video of the issue?

**Comment by violetadev** [comment]
hi @Raxiel1987, this is not a bug. Your computer has a main screen as default (you can select it in the settings, at least on mac). The app has no memory of what monitor you opened it at, or what resizing you have done to it.
