### ISSUE TITLE
Feature Request: "Back to Top" Button

### ISSUE THREAD

**Issue by Krishna3451** [responsively-org/responsively-app#1325]
### Description
Add a "Back to Top" button to improve user navigation, allowing quick return to the top of the page.

### Expected Behavior
- Button appears in the lower-right corner when users scroll down.
- Smoothly scrolls the page to the top upon click.

### Benefits
Enhances user experience by providing easier navigation on lengthy pages.

**Comment by Krishna3451** [comment]
I would love to work on this Feature. Please assign this to me.

**Comment by Sadman95** [comment]
I want to contribute on this.

**Comment by Jezyk182** [comment]
Hey, I think I can do this! I've made this feature in my other personal project
