### ISSUE TITLE
Go to Top button

### ISSUE THREAD

**Issue by KavyaBS123** [responsively-org/responsively-app#1329]
Hey @violetadev  🚀Go to Top button
can be added at the footer

**Comment by vykanand** [comment]
@KavyaBS123 @violetadev 
I think i can take up this task, @KavyaBS123 can you assign this issue to me?
My proposal for this is to create a floating button at bottom right of the screen which will have fixed position and will be visible able scrolling to bottom of the page, and on click of the button we scroll to top of the page with a js snippet code.

**Comment by violetadev** [comment]
Hi, please start working on it, no need to assign the issue.

**Comment by Shayan12456** [comment]
@violetadev I am working on it.
