### ISSUE TITLE
Avoid Windows SmartScreen

### ISSUE THREAD

**Issue by jjavierdguezas** [responsively-org/responsively-app#151]
I don't really know much about this topic, I was reading a little and they talk about doing a code signing
The issue is that this can scare new users or cause problems when installing on work computers.
![image](https://user-images.githubusercontent.com/13673443/83396140-cb3b4780-a3fb-11ea-838a-d16ce1f6049f.png)

>**Windows protected your PC**
Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.
>App: ResponsivelyApp-Setup-0.1.6.exe
>Publisher: Unknown publisher
>**[Run anyway]**          **[Don't run]**

I really don't know if this is a "right-now-issue" or it can wait until a `v1` release

**Comment by manojVivek** [comment]
Yes @jjavierdguezas you are right. This is because the windows setup file is not code-signed as of yet. So the Microsoft Defender will be showing this warning.

We will keep this issue open until we do that.

**Comment by manojVivek** [comment]
Code-signing will be done from the next release on-wards! 🎉

**Comment by jjavierdguezas** [comment]
The last version is code-signed

Before:
![image](https://user-images.githubusercontent.com/13673443/95966691-b9d36480-0e0b-11eb-9869-2603ba7f5593.png)

After:
![image](https://user-images.githubusercontent.com/13673443/95966716-c061dc00-0e0b-11eb-8fa7-bf0747f823c9.png)

It will eventually stop showing warnings as it is downloaded by multiple people (they call it _to grow a reputation "organically"_)
