### ISSUE TITLE
[Feature] Need Proxy Support

### ISSUE THREAD

**Issue by tsengkasing** [responsively-org/responsively-app#186]
Developers need to use proxy to switch to different environments.
It will be appreciated to set a proxy in user preference.
It will be better to have this feature like the extension "ProxyOmega" in Chrome.

**Comment by jjavierdguezas** [comment]
@manojVivek  maybe [this](https://www.electronjs.org/docs/api/session#sessetproxyconfig) could be util

**Comment by manojVivek** [comment]
Yes, this will be an essential feature to be added. Maybe we should have as an option to the user-preferences pane to configure it?

**Comment by jjavierdguezas** [comment]
As a Cuban developer that for many years had to browse and work through a proxy, I would be more than pleased to try to add this feature

**Comment by manojVivek** [comment]
@jjavierdguezas You go it, assigning to you. Thank you so much 😀
