### ISSUE TITLE
[Feature] Add the File menu directly to the title bar

### ISSUE THREAD

**Issue by Kidcredo** [responsively-org/responsively-app#189]
I really love this project and I have been using it for my project for quite some time now.

![image](https://user-images.githubusercontent.com/15522605/84562269-bd15f100-ad42-11ea-9526-c20d4707ead1.png)

I think it would be a good idea to add the file menu directly into the status bar on Windows and Linux as it would help optimize the screen space available and it would amazing for devices with a smaller screen
Thanks in Advance.

**Comment by Kidcredo** [comment]
Maybe we can use this library to achieve it.
https://www.npmjs.com/package/custom-electron-titlebar

**Comment by manojVivek** [comment]
@Kidcredo  That is a really great idea to increase the usable window area. Thanks for the suggestion.

**Comment by AARYAN-MAHENDRA** [comment]
Can i work on this issue.

**Comment by manojVivek** [comment]
Yes please @AARYAN-MAHENDRA.

**Comment by AARYAN-MAHENDRA** [comment]
Thanks.

**Comment by jjavierdguezas** [comment]
@itsaaryan are you still working on this? If not, tell us so we can let other contributors try

**Comment by jjavierdguezas** [comment]
@itsaaryan I'm taking over this issue ok? If you have anything to discuss related please contact us on slack

**Comment by ParamBirje** [comment]
Hello @jjavierdguezas @manojVivek @themohammadsa ,

I have implemented the custom titlebar which has the 'File Menu' and the App title together. Let me know if there are any changes required.

![custom_titlebar](https://github.com/responsively-org/responsively-app/assets/87022870/d1cca220-fa47-4772-8d06-bfb004120152)
