### ISSUE TITLE
Inactive Devices list keep reordering itself

### ISSUE THREAD

**Issue by jjavierdguezas** [responsively-org/responsively-app#234]
>Version: 0.5.0
Electron: 8.3.0
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.18362

If this is intended, then just close this issue... but I personally think it is a bit weird

When managing the devices, no matters how I drag and drop an item in the Inactive Devices list, it keeps reordering itself. Maybe I want to keep an order on that list or I made a mistake and moved the wrong device to inactives, after a drag&drop action the moved device should be where I dropped it, but that is not always the case
This only happens in the Inactive Devices list

![device list](https://user-images.githubusercontent.com/13673443/86270963-6460a800-bbcc-11ea-88ee-c4fdef7d209e.gif)

**Comment by manojVivek** [comment]
@jjavierdguezas Yeah you are right, the ordering is not taken care of when a device is dropped in the inactive list.

**Comment by TatisLois** [comment]
Hey 👋🏽 

If this is a good first issue for a contributor I’ll like to take a crack at fixing this issue!

**Comment by manojVivek** [comment]
@TatisLois That would be awesome, assigning it to you! 🙌

**Comment by manojVivek** [comment]
@TatisLois Please join us on Gitter if you have any questions along the way - https://gitter.im/responsively-app/

**Comment by manojVivek** [comment]
@TatisLois, any updates on this one?

It is perfectly alright if you got busy, just let us know. :)

**Comment by jjavierdguezas** [comment]
It's been like two months so I gave it a try (and it was tricky), 
@TatisLois don't worry there are (and will be) more issues to solve. looking forward for your contributions in the future! 💪🏻
