### ISSUE TITLE
desktop-app directory contains both a yarn and package lock file

### ISSUE THREAD

**Issue by TatisLois** [responsively-org/responsively-app#242]
I just cloned and am setting up the codebase in the `desktop-app` directory to dev locally and noticed there is both a `yarn.lock` and `package-lock.json`. Basd on the readme recommendation to run `yarn dev` I assume that yarn is the prefered lock file to install. Is that the case?

Would it make sense to drop one for the other to avoid consistency issues by trying to manage both?

**Comment by jjavierdguezas** [comment]
yeah the project has some inconsistencies
I think @manojVivek that this is a good opportunity to "normalize" the development environment: `yarn` vs `npm`, linters, code styles, pre-commit hooks, etc. We could at least write recommendations to contributors in the README

**Comment by TatisLois** [comment]
@jjavierdguezas that would be helpful - I am going through the setup for local dev and running into a few issues. I think i'll be able to get up and started but a refresh on how to contirbute and setup local would be amazing. I'd be willing to help in anyway

**Comment by manojVivek** [comment]
Yeah the `package-lock.json` got added by mistake in a contribution PR. We should delete it and stick to `yarn`.

**Comment by TatisLois** [comment]
@manojVivek 👍 can I open a PR removing it?

**Comment by manojVivek** [comment]
@TatisLois You can combine it with #234's PR maybe?

**Comment by TatisLois** [comment]
@manojVivek sounds good will do 👍
