### ISSUE TITLE
Suggestion: Updating elements in devtools should update all the screens at the same time

### ISSUE THREAD

**Issue by jeremytenjo** [responsively-org/responsively-app#268]
Great app!

Suggestion: Updating elements in devtools should update all the screens at the same time

**Comment by manojVivek** [comment]
@tenjojeremy This is a great suggestion, I have been thinking about the same recently. 🙌 
Will consider it as a high impact feature on the Roadmap.

**Comment by jeremytenjo** [comment]
Awesome work @manojVivek !
