### ISSUE TITLE
Prompt to move the app to `Applications` folder in mac if launched from somewhere else

### ISSUE THREAD

**Issue by manojVivek** [responsively-org/responsively-app#286]
Please refer to [isInApplicationsFolder](https://www.electronjs.org/docs/api/app#appisinapplicationsfolder-macos) and [moveToApplicationsFolder](https://www.electronjs.org/docs/api/app#appmovetoapplicationsfolderoptions-macos) api to implement this.

**Comment by prakashchokalingam** [comment]
Can you change my PR status from draft?
