### ISSUE TITLE
Disable Event Mirroring Globally

### ISSUE THREAD

**Issue by fabiangigler** [responsively-org/responsively-app#317]
My issue comes up in the following use case:
I already have a workflow set up that is running browser-sync, to live reload the site across browsers and real devices in the local network. It is also set up to mirror events by default already.

By default when I click or scroll in Responsively, the events are mirrored twice, resulting in an endless loop of events repeating each other. Event mirroring can currently only be disabled by clicking the disable button on every device, and it doesn't persist after a restart of the app.

I'm proposing either a global, persistent option to disable event mirroring within Responsively, or at least to persist the state of the individual buttons on each device.

**Comment by manojVivek** [comment]
@fabiangigler This is a bug that got introduced in the latest release v0.7.0. That is causing the disable event mirroring to not work and it is being looked into by @esprush. Meanwhile, you can download [v0.6.1](https://github.com/manojVivek/responsively-app/releases/tag/v0.6.1), if this is blocking you.

But nevertheless, we'll take this as a requirement to add an option to globally disable event mirroring functionality. Thanks for raising it. 👍

**Comment by ns23** [comment]
Hello

Can I work on this issue ?

**Comment by manojVivek** [comment]
@ns23 That would be awesome 🎉 

But you should be implementing this on top of https://github.com/responsively-org/responsively-app/pull/387 and not the current `master` branch. 

Please let me know so that I can assign this issue to you. 👍

**Comment by ns23** [comment]
Hi

#387 is merged into master , So I will be fixing this by create branch from master only right ?

Also can you please guide me to a  file where I should be looking in order to fix this issue?

**Comment by manojVivek** [comment]
> #387 is merged into master , So I will be fixing this by create branch from master only right ?

Yes right.

> Also can you please guide me to a file where I should be looking in order to fix this issue?

You can implement this in the same way how the screenshot option in the toolbar is implemented. You can start from here: https://github.com/responsively-org/responsively-app/blob/master/desktop-app/app/components/ScrollControls/index.js#L58

**Comment by ns23** [comment]
Okay.. I will start working on it ..

**Comment by manojVivek** [comment]
Great, assigning it to you then. 🎉 

@ns23  Please joining our Slack workspace if you want to discuss any questions you might have: https://join.slack.com/t/responsively/shared_invite/zt-h0ouywhs-IIeHj39ymz5IOrgcOa_tRA
