### ISSUE TITLE
Persist scroll position across page reloads

### ISSUE THREAD

**Issue by marcoscannabrava** [responsively-org/responsively-app#328]
Everytime you save a file the screen refreshes and scrolls to the top.
- e.g. Building a footer component on responsively becomes pretty annoying as the page scrolls back to the top everytime I save.

**Comment by manojVivek** [comment]
@marcoscannabrava You are suggesting the scroll position should be restored to the same after the reload?

**Comment by marcoscannabrava** [comment]
Exactly. If you picture someone building a footer on a homepage you'll understand what I went through yesterday. Everytime I made a change I had to go to the Responsively.app tab and scroll back down to the footer. I think it's super important, honestly.
***Congratulations for the app. It's a game changer.***

**Comment by naher94** [comment]
Ditto on this one!

**Comment by ewazlak** [comment]
Upvote!

**Comment by rafaykhawar09** [comment]
Cool

**Comment by jjavierdguezas** [comment]
hi @manojVivek maybe I can give this a try

**Comment by manojVivek** [comment]
That is great, thanks @jjavierdguezas. 🙌 

This might help: https://www.npmjs.com/package/electron-retain-webview-scroll

**Comment by esprush** [comment]
@jjavierdguezas @manojVivek came across below option in browserSync. looks like they support this out of the box.
https://www.browsersync.io/docs/options#option-scrollRestoreTechnique

**Comment by manojVivek** [comment]
@esprush  I think, this only applies when `browser-sync` is doing the reloading.

**Comment by esprush** [comment]
just checked on the latest version and this works for me. @marcoscannabrava can you confirm? 
cc: @manojVivek @jjavierdguezas think chrome 83 update handled this

**Comment by marcoscannabrava** [comment]
Awesome! It's fixed.
