### ISSUE TITLE
Add an option to clear the URL history(used for URL suggestion)

### ISSUE THREAD

**Issue by manojVivek** [responsively-org/responsively-app#341]
Add a button to the user preferences that can clear the data that is used for the Address bar suggestions.

**Comment by pajaydev** [comment]
@manojVivek  Shall I work on this ?. Do we have designs for this ?.

**Comment by manojVivek** [comment]
@pajaydev Sure, assigning this to you! 

For the design, we can add a button with `Clear Address History` text below the `Screenshot Path` input box in the UserPreferences section. Maybe we can add a top border to show the separation.

**Comment by jjavierdguezas** [comment]
@pajaydev  since it has been a long time, I have made this feature myself
