### ISSUE TITLE
Add page title to the Address Bar Suggestion items

### ISSUE THREAD

**Issue by manojVivek** [responsively-org/responsively-app#349]
Show the title before the URLs in the suggestion panel like in chrome:

<img width="694" alt="Screenshot 2020-07-25 at 11 31 21 AM" src="https://user-images.githubusercontent.com/1283424/88450166-a0ed8f80-ce6a-11ea-8b4d-04d1eb56b31e.png">

**Comment by JohnRawlins** [comment]
Hi,
I am interested in working on this issue if nobody has already. Is there anything I need to know before submitting a pull request? Thanks in advance.

**Comment by manojVivek** [comment]
@JohnRawlins Awesome, thank you so much for showing interest. I'll assign this to you. 🎉 

I don't think there is any specific catch here, but some things to watch out for:
1. The search text should search the title text too.
2. The implementation should be backward compatible with the currently saved history data.
