### ISSUE TITLE
When HTML file has an # in the name, it does not open with responsively

### ISSUE THREAD

**Issue by jjavierdguezas** [responsively-org/responsively-app#367]
>Version: 0.9.0
Electron: 9.1.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

- How to reproduce
1- create a valid html file in your file system
2- open it with responsively, it should go OK
3- rename the file and put a `#` somewhere in the name
4- open it with responsively, an `ERROR: -6 ERR_FILE_NOT_FOUND` appears

I don't know if this happens with other characters

when you open the renamed file with Chrome, it replace `#` by `%23` and when you replace it in Responsively address bar it works again

**Comment by jjavierdguezas** [comment]
it does not work from `Open HTML file` menu item nor from `Open with Responsively` OS menu

**Comment by jjavierdguezas** [comment]
maybe we need to URL encode the filepath/filename

**Comment by aUsefulMethod** [comment]
I can look into URL encoding and attempt this if there isn't anyone else working on it?

**Comment by manojVivek** [comment]
@aUsefulMethod That would be awesome, please go ahead. 🙌 

I'll assign this to you!

**Comment by aUsefulMethod** [comment]
![Screenshot (42)](https://user-images.githubusercontent.com/34969195/90319649-9e2d0a00-deff-11ea-8aa5-34dc11493fcb.png)

Getting this response when running yarn dev from desktop-app

**Comment by aUsefulMethod** [comment]
I'm so sorry, I'm on my laptop and I hadn't run npm install :/. I use too many devices. 🤦‍♂️
