### ISSUE TITLE
Open the App from the cli and load the url/filepath passed as the arg.

### ISSUE THREAD

**Issue by manojVivek** [responsively-org/responsively-app#369]
Sample Mac command can be:
```
open /Applications/ResponsivelyApp.app --args https://example.com
```

**Comment by mrfelfel** [comment]
Can you explain more? I read the source
But there seems to be such a feature in the system. So what exactly does the openWithHandler function do?

**Comment by jjavierdguezas** [comment]
Hi @mrfelfel, `openWithHandler` is a function developed as part of #330. When you use the `Open with ...` feature of the (Windows and Mac) OS it sends the path of the selected file as a cli arg (`process.argv[1]`)
So, right now you can do:
```console
$ path/to/Responsively.exe "path/to/file.html"
```
and it will open the file inside Responsively. It should work in Mac too

That only works for local files but we can extends this to anything customizable inside Responsively
To start with something we can add an `--open` arg that will tell Responsively to open it regardless of whether it is a local file path or a URL
 
```console
$ path/to/Responsively.exe --open "path/to/file.html"          // open file.html
$ path/to/Responsively.exe --open "http://localhost:3000"      // open http://localhost:3000
$ path/to/Responsively.exe --open "www.google.com"             // open www.google.com
```

I really don't know how far @manojVivek want to go with this but if you think about it we can pass as an arg anything that the user can customize by clicking on the app 😉

**Comment by manojVivek** [comment]
Yeah, `path/to/Responsively.exe "path/to/file.html"` seems better.

**Comment by jjavierdguezas** [comment]
Should we assign this to you @mrfelfel ?

**Comment by sirdarthvader** [comment]
Hey @jjavierdguezas is someone working on this issue, if not I would like to work on this.

**Comment by jjavierdguezas** [comment]
> Hey @jjavierdguezas is someone working on this issue, if not I would like to work on this.

I think there is no one
I am assigning this to you
thanks!

**Comment by jjavierdguezas** [comment]
@sirdarthvader since it has been a long time, I have made this feature myself
