### ISSUE TITLE
Screenshot blank image

### ISSUE THREAD

**Issue by Addin** [responsively-org/responsively-app#374]
When you take a Screenshot, the image looks blank. I recorded a video with the problem.

https://www.loom.com/share/5e987c5779254d20bda8506e541c488d

**Comment by manojVivek** [comment]
@Addin Can you please add the app and platform details? (`Help` menu -> `About` -> `Copy`)

I checked your website from my laptop and it works fine, attaching the screencast below. So the above details will give us more ideas on what is wrong.

![2020-08-04 09-46-48 2020-08-04 09_50_07](https://user-images.githubusercontent.com/1283424/89252914-bf0c7a00-d638-11ea-8924-130f13706109.gif)

**Comment by Addin** [comment]
Here's the data.

Version: 0.9.0
Electron: 9.1.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by manojVivek** [comment]
@Addin I have tried it with the same setup and it worked for me. 

Is it possible there is any permission problem in your system? 
If not, can you also try re-installing the app?

**Comment by Addin** [comment]
I re-installed the app and now it's in a loop when a screenshot is taken 😢 

![image](https://user-images.githubusercontent.com/6179522/89433512-0b72bb00-d708-11ea-9a55-696eae876230.png)

**Comment by manojVivek** [comment]
@Addin Can you try changing the `Screenshot Location` to a different folder, on the `User Preferences` on the left side?

**Comment by Addin** [comment]
Bingo! changing the image location works.

**Comment by manojVivek** [comment]
Great, closing this issue.
