### ISSUE TITLE
Not showing responsiveness

### ISSUE THREAD

**Issue by kushal98** [responsively-org/responsively-app#379]
Hey,

I tried running a html page which is built using aframe and I noticed when I make some changes in one screen its not changing in other screens.

Thanks

**Comment by jjavierdguezas** [comment]
hi @kushal98 what do mean by "make some changes in one screen"? are you modifiying the html code in one device via devtools?

**Comment by jjavierdguezas** [comment]
Im closing this as no further information has been given
