### ISSUE TITLE
Screenshots not showing all background images/colours correctly

### ISSUE THREAD

**Issue by richosr2** [responsively-org/responsively-app#382]
When getting screen shot some images/colours not showing correctly:

example page:
![image](https://user-images.githubusercontent.com/65107678/89704753-f359a080-d980-11ea-91c5-7bb3ff0c1a07.png)

Screen shot from program looks like:
![image](https://user-images.githubusercontent.com/65107678/89704783-4895b200-d981-11ea-9eec-a5c47f9f0e12.png)

regards
Steve

**Comment by manojVivek** [comment]
@richosr2 Can you please share a sample page URL to test it? 

Related note: If that purple background image is `position: fixed` then that will not be displayed while taking the screenshot.

**Comment by richosr2** [comment]
http://myphpsite.co.uk/1digitalis/

**Comment by manojVivek** [comment]
@richosr2 It is because that image has `position: fixed` set on it.

```
<div style="background-position: 50% 50%; background-size: cover; background-repeat: no-repeat; background-image: url(&quot;http://myphpsite.co.uk/1digitalis/assets/images/background5.jpg&quot;); position: fixed; top: 0px; left: 0px; width: 1440px; height: 748.05px; overflow: hidden; pointer-events: none; margin-top: 75.975px; transform: translate3d(0px, -75.975px, 0px);"></div>
```

The app hides those elements while taking the screen, that is a requirement as fixed Position elements get repeated while capturing full-page screenshots.

**Comment by manojVivek** [comment]
Created issue #385 to add an option to make this hiding configurable. 

Closing this one, please watch for the updates there.

**Comment by richosr2** [comment]
But if take screenshot with Firefox screenshot, the sshot is perfect;

![image](https://user-images.githubusercontent.com/65107678/89712875-e14a2300-d9bd-11ea-812f-99936693f0c7.png)

**Comment by manojVivek** [comment]
Yes, that is right. We will make a workaround in #385.
