### ISSUE TITLE
Add a user preference option to control if fixed position elements should be hidden while capturing the screenshot

### ISSUE THREAD

**Issue by manojVivek** [responsively-org/responsively-app#385]
Right now we add `responsivelyApp__ScreenshotInProgress` class to the elements that have `position: fixed` as those elements get repeated during the full page screenshot. 

But this is creating problems for some pages, so we need to make this hiding logic optional and let the user chose what is required for them.

**Comment by crperezt** [comment]
Could I take a crack at this? Were you thinking of a checkbox in the User Settings saying "Remove fixed position elements from full screenshot" or something like that?

**Comment by manojVivek** [comment]
@crperezt Awesome! That is exactly what I have been thinking. 😀
Shall I assign this issue t you if you are going to give it a go?

**Comment by crperezt** [comment]
That'd be great, thank you! Already started on it.
