### ISSUE TITLE
Persistent hover effect when Toggle Touch Mode button is activated.

### ISSUE THREAD

**Issue by jzabala** [responsively-org/responsively-app#388]
As described on https://github.com/responsively-org/responsively-app/issues/232#issuecomment-652340907 by @jjavierdguezas 

> When you click the Toggle Touch Mode button and Touch Mode is on, moving the mouse to the next button (left or right) will make it look hovered until you toggle Touch Mode again

![touchmodeissue2](https://user-images.githubusercontent.com/13673443/86234807-c521bd80-bb97-11ea-87ab-449752c6d93d.gif)

_Note: moving this to its own issue since it can be worked independently of the other problems reported on #232_

**Comment by JLambertazzo** [comment]
Found a fix for the persistent hover by changing the toggle button's event handling!

**Comment by jjavierdguezas** [comment]
Great @JLambertazzo! I'm assing it to you. Thanks!
