### ISSUE TITLE
Add a section on the website to list the contributors

### ISSUE THREAD

**Issue by manojVivek** [responsively-org/responsively-app#397]
Add a section above the footer on homepage and downloads page like below:

<img width="1680" alt="Screenshot 2020-08-16 at 4 18 30 PM" src="https://user-images.githubusercontent.com/1283424/90332659-562fe500-dfdc-11ea-8bfe-c12a19c96bfa.png">

Inspired from this link: https://insomnia.rest/download/core

**Comment by nuggetnchill** [comment]
I can try to tackle this!

**Comment by lepasq** [comment]
Hi, I'd like to work on this issue! 
I've already had a look at [this](https://github.com/Kong/insomnia.rest/blob/master/src/partials/contributors.js) and [this fetch script](https://github.com/Kong/insomnia.rest/blob/master/scripts/fetch-metrics.js) and I will try to implement the contributors list in a similar way.

**Comment by jzabala** [comment]
@lepasq Thank you! Assigned it to you. 🙌

**Comment by lepasq** [comment]
Hello again! I've worked on the contributors list for quite a while now, and this is the result that I got:
![screenshot-2020-08-19_11:56:33](https://user-images.githubusercontent.com/53230128/90620692-1272f080-e213-11ea-9f1c-2075b537947f.png)

When hovering over an avatar, a small textbox, containing the username and the contribution stats, will be displayed.
![screenshot-2020-08-19_11:59:12](https://user-images.githubusercontent.com/53230128/90621059-87dec100-e213-11ea-9cc0-bf81c530314e.png)

That section is responsive, so if you shrink the size of the browser, you will get a different result:
![screenshot-2020-08-19_11:53:59](https://user-images.githubusercontent.com/53230128/90620649-0424d480-e213-11ea-9f01-9383ce031806.png)

I have one question before submitting a PR though: in which file should I put the styling rules for the user list and the avatars?

**Comment by manojVivek** [comment]
@lepasq Awesome! 🎉 

> I have one question before submitting a PR though: in which file should I put the styling rules for the user list and the avatars?

I think you can add it to the `custom.css` file. 

Also, can you please move this section above the `Start building beautiful websites` block: 

<img width="1396" alt="Screenshot 2020-08-19 at 4 14 52 PM" src="https://user-images.githubusercontent.com/1283424/90625486-47913a00-e237-11ea-9ad3-8272d113c11e.png">

**Comment by lepasq** [comment]
![screenshot-2020-08-19_13:03:23](https://user-images.githubusercontent.com/53230128/90627557-67673480-e21c-11ea-80b3-db4db1e0ad33.png)

@manojVivek Thanks for your quick reply!
> Also, can you please move this section above the Start building beautiful websites block:

This is where I moved the section. Does it come up to your expectations?

**Comment by manojVivek** [comment]
@lepasq I was thinking this can be between that light purple and black section(not combined to the browser extensions block). With just the white background.
