### ISSUE TITLE
Show alert of some kind that SSL validation can be disabled whenever the page load fails because of SSL validation.

### ISSUE THREAD

**Issue by manojVivek** [responsively-org/responsively-app#403]

**Comment by med1001** [comment]
Hi,
Electron is based on Google's open-source Chromium.
In the chromium source code  in net_error_list.h they are listing all network errors

they write these lines in the beginning of the file:

// This file contains the list of network errors.

//
// Ranges:
//     0- 99 System related errors
//   100-199 Connection related errors
//   200-299 Certificate errors
//   300-399 HTTP errors
//   400-499 Cache errors
//   500-599 ?
//   600-699 FTP errors
//   700-799 Certificate manager errors
//   800-899 DNS resolver errors

if i have understand well this issue we need to add this alert to errors that range between 200 and 299.Is that true?

**Comment by jjavierdguezas** [comment]
Should we assign this to you @med1001 ?

**Comment by med1001** [comment]
Yes, I'll be happy to try it @jjavierdguezas .

**Comment by jjavierdguezas** [comment]
great assigned this to you @med1001

**Comment by abraham-john-paul** [comment]
Hi, can i try this issue?

**Comment by jjavierdguezas** [comment]
> Hi, can i try this issue?

thanks @abraham-john-paul 

let's give @med1001 a bit more, if we don't hear from him/her in a few days, we can assign this to you

@med1001 if you are not working on this , tell us please

maybe you want to try another issue? 😉

**Comment by jjavierdguezas** [comment]
as we have not heard anything from @med1001 I removed her/him as assignee
@abraham-john-paul if you want to work on this tell us and we'll assign it to you

**Comment by med1001** [comment]
Hello, sorry for my late response. I have opened the merge request and am ready to discuss it and improve it if needed.
