### ISSUE TITLE
Error message in-app

### ISSUE THREAD

**Issue by eugenia-carlini** [responsively-org/responsively-app#405]
Hi,

When open app, it shows me the following message error:

<img width="1138" alt="error in app" src="https://user-images.githubusercontent.com/61878414/90673436-21b36780-e22e-11ea-964d-2eceb7b88c2c.png">

Regards.

**Comment by jjavierdguezas** [comment]
hi @eugenia-carlini , could you copy paste the text of the error (the image does not show all of it)?
also, could you provide more info about your environment (OS, etc), and are you using an official release or are you playing around with the code?

**Comment by eugenia-meli** [comment]
Hi @jjavierdguezas! How are you?

I couldn't copy/paste the message error from the app. Because of that, I took a screenshot. The entire error says the following:

![image](https://user-images.githubusercontent.com/59061738/90783261-3c411b80-e2d6-11ea-94b4-58f9b65306c0.png)

My environment is macOS Catalina 10.15.4. I downloaded it from here: https://responsively.app/
If you need more data from my environment, just let me know!

I hope it helps.

**Comment by eugenia-carlini** [comment]
Hi @jjavierdguezas! How are you?

I couldn't copy/paste the message error from the app. Because of that, I took a screenshot. The entire error says the following:

![image](https://user-images.githubusercontent.com/59061738/90783261-3c411b80-e2d6-11ea-94b4-58f9b65306c0.png)

My environment is macOS Catalina 10.15.4. I downloaded it from here: https://responsively.app/

Also, I took a screenshot about the app:

![image](https://user-images.githubusercontent.com/59061738/90783736-dd2fd680-e2d6-11ea-91af-04e8cfa2f0eb.png)

If you need more data from my environment, just let me know!

I hope it helps.

**Comment by manojVivek** [comment]
@eugenia-carlini Can you please try running the following command in your terminal and then re-open the app?
```rm -rf ~/Library/Application\ Support/ResponsivelyApp```

**Comment by eugenia-meli** [comment]
It definitely worked! Thanks @manojVivek.

Regards!

**Comment by jjavierdguezas** [comment]
@eugenia-carlini glad that it worked, thanks @manojVivek 
btw, we are addressing the crash view improvements in https://github.com/responsively-org/responsively-app/issues/407

**Comment by eugenia-meli** [comment]
Great @jjavierdguezas! It's good to know! 👍
