### ISSUE TITLE
Remove routing dependencies.

### ISSUE THREAD

**Issue by jzabala** [responsively-org/responsively-app#414]
Remove unnecessary routing dependencies (`react-router`, `react-router-dom` and `connected-react-router`) and all related code: 

https://github.com/responsively-org/responsively-app/blob/6fd99970e9604fa7a89ca6e5abaf760def48d8a5/desktop-app/app/Routes.js#L19

https://github.com/responsively-org/responsively-app/blob/ddc790da2d127c1cd29fe6ff88e1ec99d83c1a33/desktop-app/app/reducers/index.js#L10

**Comment by manojVivek** [comment]
Or maybe we can keep it and make better use of it. 
Like integrating the user-preferences section to the router, so that the app's UI state can be restored via an URL? 

Just a thought.

**Comment by jzabala** [comment]
> Or maybe we can keep it and make better use of it.
> Like integrating the user-preferences section to the router, so that the app's UI state can be restored via an URL?
> 
> Just a thought.

Do you have an idea of a situation where we would use that? Because at all moments we have the user preferences in the store and for opening the app with specific args we could use something similar to the issue #369

**Comment by manojVivek** [comment]
> Do you have an idea of a situation where we would use that?

Not really, I don't have a real use-case. Just speculation, if we ever need to control the app UI from an external URL or something like that.

> and for opening the app with specific args we could use something similar to the issue #369

In this case, we will have to manually manipulate the values in the store to reflect the required state right? 
I guess, passing a specific URL to load(in the below line) and letting the router do the rest would be taken care of by the router.

https://github.com/responsively-org/responsively-app/blob/799ad0683022e814606b3290c75cf182c1bbeb0f/desktop-app/app/main.dev.js#L277

Does this make sense? 

But yeah I agree this is all for a requirement we don't have right now. 😄

**Comment by jzabala** [comment]
> In this case, we will have to manually manipulate the values in the store to reflect the required state right?
> I guess, passing a specific URL to load(in the below line) and letting the router do the rest would be taken care of by the router.

Doing it via the url or in other way, I think the code that takes those values and manipulate the store needs to exists somewhere. The only thing we'll be changing is from where the values are coming from.

I get that the libs are already in the app and they don't bothered anyone, but if we are not using them they are just making the app a little (very very little) heavier and slower (since it is more code the engine needs to process).

Also there is no risk in removing them. If we find a use case we can just revert the commit and done, libs back 😀

What do you think?

**Comment by manojVivek** [comment]
> Also there is no risk in removing them. If we find a use case we can just revert the commit and done, libs back 😀

Yes, that makes sense. We can always add it back when required.

**Comment by sidthesloth92** [comment]
Can I work on this?

**Comment by sidthesloth92** [comment]
@manojVivek Can I work on this issue? Let me know if I got this one right. Remove the `react-router`, `react-router-dom` and `connected-react-router` dependencies from `package.json`. It's code usage including it's initialization in the `redux` store.

**Comment by manojVivek** [comment]
@sidthesloth92 Yes that is right. 

Awesome, thanks for picking this issue, I'm assigning it to you! 🎉
