### ISSUE TITLE
Should it assume HTTP for localhost?

### ISSUE THREAD

**Issue by Taeluf** [responsively-org/responsively-app#433]
## Current Behavior
1. Type `taeluf.localhost` (or your own localhost subdomain)
2. [enter]
3. address bar becomes: `https://taeluf.localhost`

## Desired Behavior
When `.localhost` tld is used, route to `http://taeluf.localhost`

## My thoughts
All my sites use `HTTPS`, but not in local development. Firefox assumes `http://`, and I think other browsers do to. Or maybe there is some "dns" type lookup that determines it?  

I'm running an Apache server. In playing with `npm run start`, that also makes an `http` localserver (I did zero configuration & have very little experience with npm).

I definitely think `https://` is better for the web & should be assumed there.

I'm interested in **trying** to contribute a "fix" for this if y'all like it.

**Comment by manojVivek** [comment]
@Taeluf This totally makes sense. Thanks for suggesting it.

**Comment by Taeluf** [comment]
Starting line 294 of [AddressInput/index.js](https://github.com/responsively-org/responsively-app/blob/master/desktop-app/app/components/Addressinput/index.js)
```javascript
_normalize = (address: string) => {
    if (address.indexOf('://') === -1) {
      let protocol = 'https://';
      if (address.startsWith('localhost') || address.startsWith('127.0.0.1')) {
        protocol = 'http://';
      } else if (fs.existsSync(address)) {
        protocol = 'file://';
      }
....
```

I believe `if (address.startsWith('localhost') || address.startsWith('127.0.0.1')) {` just needs to be changed to:

```javascript
if (address.endsWith('localhost') || address.startsWith('localhost') || address.startsWith('127.0.0.1')) 
```

I had issues setting up the dev environment (for which I submitted an issue), so I'm just making note of this, either for someone else or for myself once I get the dev environment setup.

If `address` includes the port `tlf.localhost:3000` or the request uri, there'll be extra steps, of course. I wonder if the `127.0.0.1` should have an additional check, too? I'm not sure if you can subdomain ip addresses?

**Comment by jjavierdguezas** [comment]
@Taeluf should we assign this to you?

**Comment by Taeluf** [comment]
Probably not. I'm having troubles getting my environment setup (not enough extra disk space, thanks to dual-boot partitioning) & I think I'm done with it for today & not exactly sure when I'll return to it.

**Comment by jjavierdguezas** [comment]
>Probably not. I'm having troubles getting my environment setup (not enough extra disk space, thanks to dual-boot partitioning) & I think I'm done with it for today & not exactly sure when I'll return to it.

No problem at all
