### ISSUE TITLE
Undock Inspector

### ISSUE THREAD

**Issue by diego-betto** [responsively-org/responsively-app#448]
It seems that you cannot undock the inspector (you can only dock to the left or to the bottom) that is really usefull since you may have limited space. Any idea?

**Comment by manojVivek** [comment]
@diego-betto You can do it using the option in the User-preferences, screenshot below: 

<img width="358" alt="Screenshot 2020-09-04 at 3 01 47 PM" src="https://user-images.githubusercontent.com/1283424/92224660-bd480780-eebf-11ea-84a9-db8f71ed7cbe.png">

**Comment by diego-betto** [comment]
Nice, thank you
