### ISSUE TITLE
Remove the unwanted 20px padding below the menu bar on Windows

### ISSUE THREAD

**Issue by manojVivek** [responsively-org/responsively-app#457]
Remove the space shown in the below screenshot:
<img width="1215" alt="Screenshot 2020-09-17 at 8 01 51 AM" src="https://user-images.githubusercontent.com/1283424/93413221-6299ad00-f8bc-11ea-8a6d-e12ec391e5a4.png">

**Comment by lacrosse91** [comment]
@manojVivek 
Hi, can I handle this work?

**Comment by jjavierdguezas** [comment]
This is also happening in Ubuntu
![5bd1bd1a-fc43-4687-ae9f-e1d010728cc3](https://user-images.githubusercontent.com/13673443/93491993-9d2a3680-f90a-11ea-923d-564313570eb2.jpg)

**Comment by MBakirci** [comment]
For now the line `os.platform() === 'darwin' ? '20px 0 5px' : '0 0 0'`is added to fix this issue on Windows and Linux(at least Ubuntu).
