### ISSUE TITLE
Fix the crash page color scheme.

### ISSUE THREAD

**Issue by manojVivek** [responsively-org/responsively-app#469]
The crash page looks broken after the Light mode feature. 

![EigfG4-XgAcewqO](https://user-images.githubusercontent.com/1283424/93872344-a0983600-fced-11ea-840a-345579fb466b.jpeg)

**Comment by MiloshN** [comment]
Here is the same problem.

**Comment by sidthesloth92** [comment]
@jjavierdguezas Have you started to work on it? I've fixed it in local. Sorry, forgot to comment on the PR. My bad.

**Comment by jjavierdguezas** [comment]
@sidthesloth92 go for it, but yeah, next time just tell us please
