### ISSUE TITLE
Crash after upgrade

### ISSUE THREAD

**Issue by roroland** [responsively-org/responsively-app#470]
I have this crash after upgrade to latest version, already deleted settings

rm ~/Library/Application\ Support/ResponsivelyApp/Settings

.... and reinstall app, no luck

<img width="1277" alt="Screen Shot 2020-09-22 at 05 56 39" src="https://user-images.githubusercontent.com/200220/93881764-b7bb3180-fcb5-11ea-9ddb-0cf65dbaa473.png">

{"stack":"ReferenceError: commonClasses is not defined\n    at Gu (file:///Applications/ResponsivelyApp.app/Contents/Resources/app.asar/app/dist/renderer.prod.js:25:172093)\n    at renderWithHooks (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:14803:18)\n    at updateFunctionComponent (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:17034:20)\n    at beginWork (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:18610:16)\n    at HTMLUnknownElement.callCallback (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:188:14)\n    at HTMLUnknownElement.sentryWrapped (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/@sentry/browser/dist/helpers.js:74:23)\n    at Object.invokeGuardedCallbackDev (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:237:16)\n    at invokeGuardedCallback (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:292:31)\n    at beginWork$1 (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:23203:7)\n    at performUnitOfWork (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22157:12)\n    at workLoopSync (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:22130:22)\n    at performSyncWorkOnRoot (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:21756:9)\n    at /Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11089:24\n    at unstable_runWithPriority (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/scheduler/cjs/scheduler.development.js:653:12)\n    at runWithPriority$1 (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11039:10)\n    at flushSyncCallbackQueueImpl (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11084:7)\n    at flushSyncCallbackQueue (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:11072:3)\n    at scheduleUpdateOnFiber (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:21199:9)\n    at dispatchAction (/Applications/ResponsivelyApp.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.development.js:15660:5)\n    at file:///Applications/ResponsivelyApp.app/Contents/Resources/app.asar/app/dist/renderer.prod.js:25:171676","message":"commonClasses is not defined"}

**Comment by dajpes** [comment]
Same here with Linux Mint 20.3

**Comment by manojVivek** [comment]
@roroland @dajpes Can you please update the app to the latest version and try again? 
We just pushed the version `v0.13.1` fixing this.

**Comment by dajpes** [comment]
Now it works, nice.

**Comment by roroland** [comment]
It works nice... however I can't remove the banner on the right... Even if I press "dismiss" or "open"

Maybe is just me...

<img width="1278" alt="Screen Shot 2020-09-22 at 12 12 07" src="https://user-images.githubusercontent.com/200220/93903626-44beb480-fccf-11ea-93fd-3ab29e70ce8c.png">

Thanks a lot !

**Comment by manojVivek** [comment]
@roroland It is an issue too, fixed with v0.13.2. 

Sorry again for the confusion. And thanks for your patience.
