### ISSUE TITLE
App is not starting

### ISSUE THREAD

**Issue by Petrus-9** [responsively-org/responsively-app#472]
First install on Windows gives me a almost completely blank screen with only an emoji and 3 buttons (with text Copy and Create issue).
For just a second I can see the responsive screens, but they disappear after that.

Any idea what is happening here?

Regards,
Petrus

**Comment by jjavierdguezas** [comment]
hi, we are investigating in #470, closing this as duplicated

**Comment by manojVivek** [comment]
@Petrus-9  Can you please update the app to the latest version and try again? 
We just pushed the version `v0.13.1` fixing this.

**Comment by Petrus-9** [comment]
Yes, working.

Probably the version number 13 that is the course.

Thanks for quick response and great software.

Regards

------------------
Locatie 9
Brandestraat 9
4931 AV Geertruidenberg
+316 225 38 215

[image]

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Op dinsdag 22 september 2020 16:33, Manoj Vivek <notifications@github.com> schreef:
