### ISSUE TITLE
App is crashing, not stopped working since an update.

### ISSUE THREAD

**Issue by DamilolaAjayi** [responsively-org/responsively-app#476]
My app auto updated yesterday and since then I have been seeing this anytime I open it. I can't do anything on the app.

![Screenshot (107)](https://user-images.githubusercontent.com/16501237/93943473-7e70d900-fd2a-11ea-90e9-c8a471cf06a9.png)

**Comment by jjavierdguezas** [comment]
Hi  @DamilolaAjayi ensure you have installed v0.13.2
We made some hot fixes today for this issue (see #470 and #472)
