### ISSUE TITLE
Top right corner bar is not clickable?

### ISSUE THREAD

**Issue by MiloshN** [responsively-org/responsively-app#480]
[![N|Bug](https://i.ibb.co/kmQqBKv/Screenshot-1.png)](https://i.ibb.co/kmQqBKv/Screenshot-1.png)

I can't click on any of these items in the screenshot.

Version: 0.13.2
Electron: 9.1.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

Thanks.

**Comment by jjavierdguezas** [comment]
Hi @MiloshN can you provide more info?
I can't reproduce it and I have same environment
Does it happen after an specific action or just after opening the app?

**Comment by MiloshN** [comment]
Hi @jjavierdguezas , 
I don't know how, but after reloading the app, now works.
