### ISSUE TITLE
[Feature] Navigate to CSS selector

### ISSUE THREAD

**Issue by jjavierdguezas** [responsively-org/responsively-app#492]
Add a way to type in a CSS selector and all the devices will automatically scroll to it

**Hints**
https://developer.mozilla.org/es/docs/Web/API/Element/scrollIntoView

![scrollToView](https://user-images.githubusercontent.com/13673443/95027140-9c2d2f00-0696-11eb-9e57-74466b90369a.gif)

**Comment by AngelicHeaven** [comment]
Hello, I would like to work on this.

**Comment by jjavierdguezas** [comment]
great @AngelicHeaven assigning this to you
Please come any join us in Slack if you need to discuss anything related
Also, keep in mind that #493 could be done relying on this, so think about it

**Comment by jjavierdguezas** [comment]
@AngelicHeaven  I was thinking in something like this

![image](https://user-images.githubusercontent.com/13673443/95136457-6eafb680-0766-11eb-9002-96a4fc981979.png)

![image](https://user-images.githubusercontent.com/13673443/95136493-7bcca580-0766-11eb-97b7-3ba16a3498d8.png)

![image](https://user-images.githubusercontent.com/13673443/95136600-b6ced900-0766-11eb-9df2-669384863f8e.png)


cc: @manojVivek @sidthesloth92 @jzabala

**Comment by jjavierdguezas** [comment]
This is the icon used in the mockups but @manojVivek could provide a better one
```jsx
import React, {Fragment} from 'react';

export default ({width, height, color, padding, margin, style}) => (
  <Fragment>
    <svg
      viewBox="0 0 1024 1056"
      xmlns="http://www.w3.org/2000/svg"
      xmlnsXlink="http://www.w3.org/1999/xlink"
      width={width}
      height={height}
      fill={color}
      style={{padding, margin, ...style}}
      className="navigatorIcon"
    >
      <path
        d="M1021 747l-82-151l-6-11q-5-8-15-10q-4-1-8.5-.5T901 578l-10 6v1l-146 98q-5 3-8 9t-3 12t3 12l7 7q4 8 14 9t18-4l87-60q-15 124-105 210.5T544 977V335h128q13 0 22.5-9.5T704 303t-9.5-22.5T672 271H543l-1-1v-1q43-11 71-46t28-80q0-53-37.5-91t-91-38T421 52t-38 91q0 45 28 80t71 45v2l-1 1H352q-13 0-22.5 9.5T320 303t9.5 22.5T352 335h128v642q-124-12-213.5-98T161 668l87 60q8 5 18 4t14-9l7-7q2-4 2.5-9t-.5-9.5t-3.5-8.5t-6.5-6l-146-99l-10-6q-8-6-17-3q-5 1-8.5 3.5T91 585l-6 11L3 747q-5 9-2.5 18.5T11 780l9 4q8 5 17 1.5T51 773l48-89q22 154 139.5 256T512 1042t273.5-102T925 684l48 89q5 9 14 12.5t17-1.5l9-4q8-5 10.5-14.5T1021 747zM448 143q0-27 19-46t45.5-19t46 19t19.5 46q0 11-3.5 20.5T565 181t-14 14t-18 9.5t-21 3.5q-5 0-10-1t-10-2.5t-9.5-4t-8.5-5.5t-7.5-6.5t-6.5-7.5t-5.5-8.5t-4-9t-2-10t-.5-10.5z"
        fill="currentColor"
      />
    </svg>
  </Fragment>
);

```

**Comment by itsaaryan** [comment]
If Its all right ,Can I work on this Issue

**Comment by jjavierdguezas** [comment]
> If Its all right ,Can I work on this Issue

Hi @itsaaryan, I'm sorry but @AngelicHeaven is already working on this. You can take a look on other issues: [here](https://github.com/responsively-org/responsively-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) 
Thanks for your help 👊 !

**Comment by itsaaryan** [comment]
ok sure, no problem
