### ISSUE TITLE
[Feature] Page Navigator

### ISSUE THREAD

**Issue by jjavierdguezas** [responsively-org/responsively-app#493]
Add a way to select a "section" HTML tag (`<h1/>`, `<h2/>`,... `<section/>`, `<div />` etc) and make possible to jump up and down between them within the page. (keeping in sync all devices)

**Hints**
something like [this](http://jsfiddle.net/shlomohassid/6r1h687k/) but allowing to select the HTML tag to jump

_Related to #492_

**Comment by jjavierdguezas** [comment]
I was thinking in something like this (combining #492  and #493)

![image](https://user-images.githubusercontent.com/13673443/95136457-6eafb680-0766-11eb-9002-96a4fc981979.png)

![image](https://user-images.githubusercontent.com/13673443/95136493-7bcca580-0766-11eb-97b7-3ba16a3498d8.png)

![image](https://user-images.githubusercontent.com/13673443/95136600-b6ced900-0766-11eb-9df2-669384863f8e.png)


cc: @manojVivek @sidthesloth92 @jzabala 

_(these mockups are based on PR #400)_

**Comment by lenmorld** [comment]
Hi, I would like to take a stab at this if it's not taken yet

**Comment by manojVivek** [comment]
@lenmorld As JJ was mentioning this one depends on #492. 

Can you please select some other issue from this list: https://github.com/responsively-org/responsively-app/labels/help%20wanted ?
