### ISSUE TITLE
Create Issue and PR templates for the Repo

### ISSUE THREAD

**Issue by sidthesloth92** [responsively-org/responsively-app#498]
The idea is to create an issue and PR template so that it's much easier to report bugs and to lay down some basic requirements for a PR.

P.S: The idea is not to scare people away from reporting issues or raising PR's though.. 👻

**Comment by sidthesloth92** [comment]
# For Issue Creation

🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅

Hi there! 😄

To expedite issue processing please search open and closed issues before submitting a new one. Existing issues often contain information about workarounds, resolution, or progress updates.

🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅-->

# 🐞 bug report

### ✍️ Description
A clear and concise description of the problem.

### 🕵🏼‍♂️ Is this a regression?
Did this behavior use to work in the previous version?

### 🔬 Minimal Reproduction
Clear steps to re-produce the issue. 

### 🌍  Your Environment
Press `Ctrl/Cmd + F1` and paste it here.
<pre><code>

</code></pre>

### 🔥 Exception or Error or Screenshot
<pre><code>

</code></pre>

**Comment by sidthesloth92** [comment]
# 🚀 feature request

### 📝  Description
A clear and concise description of the problem or missing capability.


### ✨ Describe the solution you'd like
If you have a solution in mind, please describe it.


###  ✍️ Describe alternatives you've considered
Have you considered any alternative solutions or workarounds?

**Comment by sidthesloth92** [comment]
Pull Request

### PR Type
What kind of change does this PR introduce?

Please check the one that applies to this PR using "x".  <-- Will be commented out. Only the creator of PR can see.

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

### PR Checklist
Please check if your PR fulfills the following requirements: 

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### What is the current behaviour?
Please describe the current behaviour that you are modifying or link to a relevant issue. Screenshots if it's a visual change. <-- Will be commented out. Only the creator of PR can see.

### What is the new behaviour?

### Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications below. <-- Will be commented out. Only the creator of PR can see.

### Other information

**Comment by sidthesloth92** [comment]
@manojVivek @jjavierdguezas  Certain lines will be commented out in the actual issue/PR. I just added them here for review. Once we have finalized the verbiage, I'll create a PR for the same.

**Comment by manojVivek** [comment]
@sidthesloth92 For the pull request format, most of this info will already be there on the referenced issue. So should we need these added again?

**Comment by sidthesloth92** [comment]
Totally valid, I'll remove some of the stuff from the Issues.

**Comment by sidthesloth92** [comment]
@manojVivek I've leaned it down.

**Comment by manojVivek** [comment]
@sidthesloth92 To be honest, it still feels like too much information to me. 😀  Questions inline.

> ### 📓 PR Type
> What kind of change does this PR introduce?

Can we change this to something like "reference issue"? So that we can have the issue linked to the PR.

> ### ✔️ PR Checklist
> Please check if your PR fulfils the following requirements:
> 
> * [x]  The commit message follows our guidelines
> * [ ]  Tests for the changes have been added (for bug fixes / features)
> * [ ]  Docs have been added / updated (for bug fixes / features)

I feel these are valid only after the standards have been defined and followed. We don't have a commit message guidelines. And we don't have base unit-test scenarios setup. I feel these points will be effective only after those things are in place.

> 🆕 What is the new behaviour?

This will be covered in the referenced issue too right?



@jjavierdguezas Please let us know your thoughts too.

**Comment by jjavierdguezas** [comment]
@manojVivek @sidthesloth92 
The bug/feature templates are ok to me
I agree with @manojVivek about the PR template, for now we just need these points:
 - related issue (_"please link the related issue, use # before the issue number and use the [verbs](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) 'fixes' , 'resolves' , etc to auto link it"_) 
 - Changes to help the code review and manual tests (_"please provide a description of your solution if it is not clear in the related issue, or you made a breaking change, there is an interesting topic to discuss, you have questions or there is an issue with electron or another library that you sorted"_)
  - Screenshot (_"please include screenshots, gif or video of your work before and after if that helps to understand it better"_)

I think we can see the other things in the commits

**Comment by sidthesloth92** [comment]
@manojVivek and @jjavierdguezas All done.. :D Thanks for your inputs.. D @manojVivek The checklist was more for the future, we will soon get there.. 🗡️

**Comment by manojVivek** [comment]
@sidthesloth92 It looks good now, please let's go ahead.
We can tweak it by observing the usage.
