### ISSUE TITLE
Bug: Opening Device Manager with dev tools open breaks layout

### ISSUE THREAD

**Issue by sidthesloth92** [responsively-org/responsively-app#509]
# 🐞 bug report

### ✍️ Description

When you have dev tools open before opening the device manager the dev tools overlaps the modal breaking layout and also making it not possible to close the modal.

### 🕵🏼‍♂️ Is this a regression?
Yes

### 🔬 Minimal Reproduction

- Open App.
- Right-click on any device and then click Inspect.
- Now click on the device drawer icon from the left pane.
- Click on Customize.

### 🌍 Your Environment
<pre><code>
Version: 0.13.2
Electron: 9.1.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.3.0
</code></pre>

### 🔥 Exception or Error or Screenshot

When dev tools is open to the right,
<img width="1440" alt="Screenshot 2020-10-10 at 21 35 06" src="https://user-images.githubusercontent.com/4656109/95659871-b60cbd00-0b41-11eb-88d2-32b331164fd4.png">

When dev tolls is open at the bottom,
<img width="1440" alt="Screenshot 2020-10-10 at 21 35 18" src="https://user-images.githubusercontent.com/4656109/95659879-bb6a0780-0b41-11eb-94e2-81e5a2658d61.png">

**Comment by sidthesloth92** [comment]
The best solution I can think of is to close the dev tools when we open the dialog. Reasons being,
1. The dialog already has z-index of 1300 given by material UI. So I guess it's not possible to make it appear over the dev tools.
2. The user might remove the device that he/she is inspecting. So closing the dev tools kinda resets the flow.

**Comment by manojVivek** [comment]
This is because the `devtools` window is a separate window overlapped on the main window. So they are two different DOM. This is a challenge. The only solution I can think of is to close the `devtools` window when the device manager is opened.
