### ISSUE TITLE
🐞 The screen turns white when clicking the help icon on the Manage extension section

### ISSUE THREAD

**Issue by Kidcredo** [responsively-org/responsively-app#514]
# 🐞 bug report

### ✍️ Description

Clicking the help icon on the Manage extension is changing background color of the app

### 🕵🏼‍♂️ Is this a regression?

 Not sure

### 🔬 Minimal Reproduction

Click the help icon in the manage extension section

### 🌍 Your Environment

<pre><code>
Version: 0.14.0
Electron: 9.3.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
</code></pre>

### 🔥 Exception or Error or Screenshot

![tGTZb9jUSK](https://user-images.githubusercontent.com/15522605/96012911-31b58500-0e34-11eb-919a-7e719d0a4ef4.gif)

**Comment by jjavierdguezas** [comment]
good catch @Kidcredo 
This should be easy to fix
