### ISSUE TITLE
Show link url on hover

### ISSUE THREAD

**Issue by lambda0xff** [responsively-org/responsively-app#516]
# 🚀 Feature Request

### 📝 Description
In standard browsers, hovering over a link triggers the display of the full url at the bottom left of the screen.
This is not replicated in responsively.

### ✨ Describe the solution you'd like
Same behaviour as standard browsers, ie display link url

**Comment by rishichawda** [comment]
Hey, can I take up this one? Might be a nice way for me to start exploring the application 😄

**Comment by jjavierdguezas** [comment]
hi @rishichawda , of course you can. I'm assigning this to you. Remember that you can discuss it with us on Slack

**Comment by rishichawda** [comment]
Great! I'll ping you if I need help figuring something out. 😄

**Comment by itsaaryan** [comment]
If its all right shall i take this issue?

**Comment by jjavierdguezas** [comment]
> If its all right shall i take this issue?

Hi @itsaaryan, I'm sorry but @rishichawda  is already working on this. You can take a look on other issues: [here](https://github.com/responsively-org/responsively-app/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22)
You need to check the *Assignees* section of the issue and if it has the `help-wanted` tag. If the issue has no assignee and it has the tag then you can request it
I hope you will try with another (available) one. Thanks💪

**Comment by itsaaryan** [comment]
Sure
