### ISSUE TITLE
Option to set blank page on application launch

### ISSUE THREAD

**Issue by alanw83** [responsively-org/responsively-app#521]
# 🚀 Feature Request

### 📝 Description

On launching the application all the viewpoints are refreshed and load Google.com. Please add an option to have it load a blank page so we don't have to wait for them all to load before using the application.

### ✨ Describe the solution you'd like

Blank page on startup checkbox in the settings menu.

**Comment by jjavierdguezas** [comment]
Meanwhile, you can always set a lighter website or even a blank html file as your homepage from your own file system
![image](https://user-images.githubusercontent.com/13673443/97061376-ed925500-1596-11eb-9e53-fa50a40acc4f.png)

**Comment by alanw83** [comment]
Thankyou blank html does load faster

**Comment by jjavierdguezas** [comment]
@manojVivek should we go and make a special `blank` or `lighter` default home or do you think that https://github.com/responsively-org/responsively-app/issues/521#issuecomment-715629147 is enough ?

**Comment by alanw83** [comment]
@jjavierdguezas to be specific the issue I have is 9 devices loading when I launch the app. They still take time loading from local drive its just faster.

Maybe having an option to not refresh the devices every time the application is launched is a better solution?

**Comment by manojVivek** [comment]
> @manojVivek should we go and make a special `blank` or `lighter` default home or do you think that [#521 (comment)](https://github.com/responsively-org/responsively-app/issues/521#issuecomment-715629147) is enough ?

@jjavierdguezas I think we should have a user preference option to set the default URL to load on start, that can have options as "Blank" or "Homepage". 

What do you think about this?

**Comment by jjavierdguezas** [comment]
> > @manojVivek should we go and make a special `blank` or `lighter` default home or do you think that [#521 (comment)](https://github.com/responsively-org/responsively-app/issues/521#issuecomment-715629147) is enough ?
> 
> @jjavierdguezas I think we should have a user preference option to set the default URL to load on start, that can have options as "Blank" or "Homepage".
> 
> What do you think about this?

That's a good idea

**Comment by bikingbadger** [comment]
Could I have a go at this? Is it assigned to anyone yet?

**Comment by jjavierdguezas** [comment]
> Could I have a go at this? Is it assigned to anyone yet?

HI @bikingbadger, I am assigning this to you, thanks!
Please join us on slack if you want to discuss this
