### ISSUE TITLE
[Feature] Mirrored DevTools

### ISSUE THREAD

**Issue by malvese** [responsively-org/responsively-app#523]
### 📝 Use a single DevTools pane for all devices

 ✨ It is a feature found in other similar products. One of them I used is the open source Emmet Re:view (http://re-view.emmet.io/) but it is no longer maintained and often doesn't work.
With this feature you can open DevTools, make changes and see them applied immediately to every device. It makes responsive work very fast, as you don't have to constantly switch between devices and make the same changes to several devices.

 ✍️ I saw an issue about a CSS editor (#386) that could somewhat be used the same way. But I believe they solve different use cases: CSS editor to _add_ arbitrary CSS, Mirrored DevTools to modify/tweak _existing_ CSS. I believe Mirrored DevTools would be a lot faster and intuitive for that latter use case (which in my opinion is the most common).

**Comment by jjavierdguezas** [comment]
Hi @malvese, thanks for your comments 
Yes, this is the most desired feature by all and we are working on it, but it is not an easy task
You can follow the progress in #268
Meanwhile, I am closing this one

**Comment by malvese** [comment]
Oh sorry I didn't find this issue when I searched. Good to know you are on it. Thank you for your work!
