### ISSUE TITLE
Not a bug, but a typo

### ISSUE THREAD

**Issue by abbydigital** [responsively-org/responsively-app#526]
In the lower right corner popup on first run, it said to "stare the github repo."

I think you must have meant "share."

**Comment by jjavierdguezas** [comment]
![image](https://user-images.githubusercontent.com/13673443/97558146-01491b80-19dc-11eb-913c-966921f5d47d.png)

@manojVivek , Should it say "star**r**ing"? 🤔 (To give a ⭐)
https://docs.github.com/en/free-pro-team@latest/rest/reference/activity#starring

**Comment by abbydigital** [comment]
I see.  I did not know about the Stars on Github.  According to the Github doc, that would be "starring."

**Comment by jjavierdguezas** [comment]
fixed
![image](https://user-images.githubusercontent.com/13673443/97564535-0494d500-19e5-11eb-9ebf-f4a52ef85a88.png)

**Comment by manojVivek** [comment]
Good catch guys! 😄
