### ISSUE TITLE
Can't disable spell checker when or after using dev tools

### ISSUE THREAD

**Issue by XVonRad** [responsively-org/responsively-app#531]
# 🐞 bug report

### ✍️ Description

My page has non-english words. The spell checker is activated as soon as I open dev tools. The red squiggly red lines under unrecognized words ruin the page rendering. From then on only a full refresh will deactivate the spell checker.

### ✨ Describe the solution you'd like

A setting where spell check can be turned on and off

### ✍️ Describe alternatives you've considered

Disabling spell checking at OS level (Windows 10 in my case).

### 🔬 Minimal Reproduction

See description
### 🌍 Your Environment
Windows 10

**Comment by jjavierdguezas** [comment]
Hi @XVonRad , can you please share a screenshot, gif or video showing the issue?

**Comment by jjavierdguezas** [comment]
Maybe we can play around the `spellcheck` prop of `BrowserWindow` and `webview` (`webpreferences`)
https://www.electronjs.org/docs/tutorial/spellchecker

```tsx
win = new BrowserWindow({
  spellcheck: false,
  .....
});



<webview
    webpreferences="spellcheck=no"
    ....
/>
```

**Comment by XVonRad** [comment]
> Hi @XVonRad , can you please share a screenshot, gif or video showing the issue?


[Responsively 2020-11-08 16-09-15.zip](https://github.com/responsively-org/responsively-app/files/5506558/Responsively.2020-11-08.16-09-15.zip)

Hi @jjavierdguezas 
I've uploaded a screen video showing that once I've click Enable Design Mode, the spell checker activates and stays on after I disable Design Mode.
Note: I never even wanted to enter design mode actually. It's just that I more often than not click on it because it's so close to 'Inspect Element' . If the button bar layout was different I'd probably never have had this issue!

**Comment by jjavierdguezas** [comment]
I see it now @XVonRad .. yes I think that a toggle in user preferences to activate/deactivate spell checker will be useful
