### ISSUE TITLE
Page interactions are not the same across mirrored devices 

### ISSUE THREAD

**Issue by talyh** [responsively-org/responsively-app#532]
# 🐞 bug report

### ✍️ Description

After scrolling a bit through a page and then clicking on some of the items, the event target is not consistently perceived across devices

### 🕵🏼‍♂️ Is this a regression?

Can't say. First time trying Responsively.

### 🔬 Minimal Reproduction

1. Setup devices:
    - Generic Laptop
    - iPhone 6/7/8
    - iPhone X
    - iPad (vertical)
2.  Open https://www.properly.ca/sell/ppr/5A_Ur1W7THSxBb-Vua05bA/proper-price-report
3.  Scroll down until you see "cards" underneath a map
4. Click on the image in the first card

(**NOTE:** The content in this page is calculated dynamically, so there's a slight chance that no cards will show when loading. If that's the case, a different link can be provided at that time)

### 🌍 Your Environment

<pre><code>
Version: 0.15.0
Electron: 9.3.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.5.0
</code></pre>

### 🔥 Exception or Error or Screenshot

![resposively error](https://user-images.githubusercontent.com/23743595/98559068-2a876880-2274-11eb-92e7-3be41bd4a0e1.gif)

**Comment by manojVivek** [comment]
@talyh Sorry for the delay here.

The Page interaction mirror only works as long as the DOM structure is the same across the devices. We use browser-sync to do the event mirroring and it employs an `XPath` like structure to propagate events of an element. 
So if the DOM structure is different across the devices then the mirroring might not work accurately.

**Comment by talyh** [comment]
@manojVivek - Thanks for the info.

In this case, the page structure was the same across devices I believe (meaning same DOM nodes, even if their styling placed them differently).

As mentioned above though, that page is no longer available so hard to know for sure. Let me know if it's useful to try and find another scenario where this happens.

**Comment by manojVivek** [comment]
@talyh If this happening on a page with a similar DOM structure across the devices then please provide us that URL. 
That will be very helpful to debug it.

**Comment by talyh** [comment]
Since out mobile/desktop menus have changed and are separate implementations now, I no longer can provide an example where the DOM structure is the same across viewports.
I'm closing this issue for now.
