### ISSUE TITLE
Save Layout settings

### ISSUE THREAD

**Issue by deadcoder0904** [responsively-org/responsively-app#534]
# 🚀 Feature Request

### 📝 Description

I always want a `Horizontal` layout but it always switches back to `FlexiGrid`

### ✨ Describe the solution you'd like

Save whatever layout I select before exiting the app & show me the same layout when I open the app.

At least, that's what Desktop Apps are supposed to do :)

**Comment by kiwan97** [comment]
Hello, I'm a college student studying coding.
May I take this Issue?

**Comment by jjavierdguezas** [comment]
> Hello, I'm a college student studying coding.
> May I take this Issue?

Hello @kiwan97 of course you can! I am assigning this to you
Please come to slack if you want to discuss anything related
Thanks! 💪

**Comment by deadcoder0904** [comment]
Great job @kiwan97 👏

**Comment by kiwan97** [comment]
Thanks for giving me a chance! @jjavierdguezas @deadcoder0904
