### ISSUE TITLE
Feature/Testing Profiles

### ISSUE THREAD

**Issue by Hahlh** [responsively-org/responsively-app#539]
# 🚀 Feature Request

### 📝 Description
Being able to group certain devices into definable "testing profiles", especially since only 5 devices at a time work.

For example:

Testing profile: extra-large
1. MacBook Pro 13
2. MacBook Pro 16
3. 4k
4. 5k

Testing profile: desktop / laptop
1. 1920x1080
2. 1440x900
3. 1366x768
4. Laptop with MDPI screen - 1280x800

Testing profile: tablet
1. Ipad
2. Surface Go
3. Onyx Boox Note 2

Testing profile: mobile
1. Iphone X
2. Samsung S7
3. Iphone 5SE
4. Galaxy Fold

Selecting the profile would activate the devices.

It would also be great to import device libraries / profiles from other users or query / import [statcounter](https://gs.statcounter.com/screen-resolution-stats#monthly-201910-202011-bar) to get screen sizes by current usage statistics, but for that I should likely open a separate issue.

Thanks to all contributors for the awesome tool! 
You are making responsive design so much easier.

**Comment by sukhiboi** [comment]
I wanted to contribute in opensource. I'll try to work on this in my free time or weekends.
Are there any guidelines on how to contribute?

**Comment by cjordan223** [comment]
Hi there,
I am looking into good first issues to start with, and I would love to work on this. Please let me know if you need any other info, I've used your app for my own web dev projects with Node.js & React.

**Comment by Bhavika-Chandra** [comment]
1. Create a data structure to store the device profiles and their associated screen resolutions. This can be a simple JSON, YAML, or JavaScript object structure. 
2. Design a UI that allows users to select a testing profile from a dropdown or toggle menu. When a profile is selected, the corresponding devices should be activated. In a web interface, this could be a simple form with a dropdown list populated by the profiles defined in the JSON. 
3. If your system is backend-driven, store the profiles in a database or configuration file, then expose an API endpoint for retrieving and activating the profiles. The backend could be implemented in Node.js or any other server-side framework.
4. You’ll need to write logic to integrate with the testing tool you are using (e.g., WebDriver, BrowserStack, etc.) to activate the selected devices. This will depend on the tool's API or capabilities.
5. This part can be developed later as an enhancement. You can fetch screen size statistics from a service like StatCounter and dynamically create profiles. You may use StatCounter's API or web scraping to gather data and update the profiles.

**Comment by manojVivek** [comment]
This feature is implemented.
