### ISSUE TITLE
Missing horizontal scrollbar

### ISSUE THREAD

**Issue by tranlamnhatnam** [responsively-org/responsively-app#553]
# 🐞 bug report

### ✍️ Description

I have 5 screens respectively (1280px, 1024px, 768px, 640px, 375px) with layout is horizontal. At a certain zoom, the horizontal scrollbar disappears.  I my case, if zoom is 50% or higher, the horizontal scroll bar will not display and 40% or less then it appeared. (Arrows key still working)

I realized that once zoom in large enough, the gift box icon (changelog) in the bottom left corner disappears, the vertical scrollbar appears, the horizontal scrollbar will disappear.

### 🔬 Minimal Reproduction

- Open app
- Set layout to **Horizontal**
- Add 5 or more devices
- Zoomin and out to check how horizontal scroollbar appeare

### 🌍 Your Environment

<pre><code>
Version: 0.15.0
Electron: 9.3.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
</code></pre>

### 🔥 Exception or Error or Screenshot

Zoom 50%+
![50](https://user-images.githubusercontent.com/1934536/106081411-6fbc8780-614b-11eb-9d3d-1168352d54af.png)

Zoom 40%-
![40](https://user-images.githubusercontent.com/1934536/106081422-74813b80-614b-11eb-97c3-a9e3f28da5c1.png)

**Comment by jjavierdguezas** [comment]
good catch @tranlamnhatnam !

**Comment by lucievr** [comment]
I would like to have a go at fixing this

**Comment by flopezre** [comment]
Confirmed. I create an app using Materialize and the horizontal scroll bar disappears
Gif:
![Materialize_Bug](https://user-images.githubusercontent.com/4932575/107725480-26c90f00-6cc5-11eb-96f0-407881f6a48f.gif)

Cheers
