### ISSUE TITLE
Send per-device User-Agent / HTTP header

### ISSUE THREAD

**Issue by bugnumber9** [responsively-org/responsively-app#558]
# 🚀 Feature Request

### 📝 Description

We're using Mobile Detect Library (http://mobiledetect.net/) which "uses the User-Agent string combined with specific HTTP headers to detect the mobile environment".
Looks like Responsively App doesn't send device-specific User-Agent strings and/or HTTP headers. It would be great if it did since sometimes one has to use this type of mobile/tablet detection rather than just the viewport sizes.

**Comment by jjavierdguezas** [comment]
Hi @bugnumber9 
Could you tell us which device is not being detected correctly? 
I tested some of the built-in ones on http://demo.mobiledetect.net/ and it seems to work well

**Comment by bugnumber9** [comment]
I apologize, looks like I was stupid :) Made a bug in my own code and didn't notice it for several days.
Sorry!
