### ISSUE TITLE
Error: -107 

### ISSUE THREAD

**Issue by bennniii** [responsively-org/responsively-app#559]
when visiting a webpage without an SSL certificate ([www.goldene-krone.de](http://www.goldene-krone.de)), i'm only presented an "Error: -107" (ERR_SSL-PROTOCOL_ERROR).

i have disabled SSL validation in the settings but the problem remains persistent. 

running ResponsivelyApp 0.15.0 on MacMini (M1, 2020), MacOS 11.2.2 (20D80)

**Comment by jjavierdguezas** [comment]
it worked for me...
![image](https://user-images.githubusercontent.com/13673443/117648352-669d7680-b18e-11eb-8ae9-10cdbe66e5eb.png)

**Comment by manojVivek** [comment]
Works for me as well.

**Comment by jjavierdguezas** [comment]
closing this as no further information has been given and we cannot reproduce it
