### ISSUE TITLE
Please change the app's icon :)

### ISSUE THREAD

**Issue by webenadam** [responsively-org/responsively-app#560]
This app is amazing, why shouldn't the icon be also ? :)

I can design one for you if you'll just say you will consider using it (u don't have to promise :)

**Comment by jjavierdguezas** [comment]
Hi @webenadam we are discussing this in https://github.com/responsively-org/responsively-app/issues/357 you can join us there
Meanwhile I am closing this as duplicated
(and btw, I **love** our icon 😉  )
