### ISSUE TITLE
[Security] How can I report a vulnerability?

### ISSUE THREAD

**Issue by Ry0taK** [responsively-org/responsively-app#563]
Hello Responsively team,
I'm a security researcher who contacted you in a direct message on Twitter.

It has been 90 days since I reported a vulnerability, so I'm opening this issue.
I won't mention the details of the vulnerability in this issue. However, I would like to know how to report a vulnerability.

Best regards,
RyotaK

**Comment by jjavierdguezas** [comment]
I suggest you contact @manojVivek on Slack
