### ISSUE TITLE
no mountable file system

### ISSUE THREAD

**Issue by asitaaa** [responsively-org/responsively-app#565]
# 🐞 bug report

when I try to install the app, it says 'no mountable filesystem'

### 🌍 Your Environment

<pre><code>

</code></pre>

### 🔥 Exception or Error or Screenshot

<pre><code>

</code></pre>

**Comment by asitaaa** [comment]
Initializing…
DIBackingStoreInstantiatorProbe: interface  0, score      100, CBSDBackingStore
DIBackingStoreInstantiatorProbe: interface  1, score    -1000, CBundleBackingStore
DIBackingStoreInstantiatorProbe: interface  2, score    -1000, CRAMBackingStore
DIBackingStoreInstantiatorProbe: interface  3, score    -1000, CDevBackingStore
DIBackingStoreInstantiatorProbe: interface  4, score    -1000, CCURLBackingStore
DIBackingStoreInstantiatorProbe: interface  5, score    -1000, CVectoredBackingStore
DIBackingStoreInstantiatorProbe: interface  0, score      100, CBSDBackingStore
DIBackingStoreInstantiatorProbe: interface  1, score    -1000, CBundleBackingStore
DIBackingStoreInstantiatorProbe: interface  2, score    -1000, CRAMBackingStore
DIBackingStoreInstantiatorProbe: interface  3, score    -1000, CDevBackingStore
DIBackingStoreInstantiatorProbe: interface  4, score    -1000, CCURLBackingStore
DIBackingStoreInstantiatorProbe: interface  5, score    -1000, CVectoredBackingStore
DIFileEncodingInstantiatorProbe: interface  0, score    -1000, CEncryptedEncoding
DIFileEncodingInstantiatorProbe: interface  0, score      900, CUDIFEncoding
DIFileEncodingNewWithBackingStore: CUDIFEncoding
DIFileEncodingNewWithBackingStore: instantiator returned 0
DIFileEncodingInstantiatorProbe: interface  0, score    -1000, CSegmentedUDIFEncoding
DIFileEncodingInstantiatorProbe: interface  1, score    -1000, CSegmentedUDIFRawEncoding
DIDiskImageInstantiatorProbe: interface  0, score     1000, CUDIFDiskImage
DIDiskImageInstantiatorProbe: interface  1, score        0, CSparseBundleDiskImage
DIDiskImageInstantiatorProbe: interface  2, score        0, CSparseDiskImage
CRawDiskImage: data fork length 0x0000000006C21A1F (113383967) not a multiple of 512.
DIDiskImageInstantiatorProbe: interface  3, score     -100, CRawDiskImage
DIDiskImageInstantiatorProbe: interface  5, score     -100, CShadowedDiskImage
DIDiskImageInstantiatorProbe: interface  6, score     -100, CWrappedDiskImage
DIDiskImageNewWithBackingStore: CUDIFDiskImage
DIDiskImageNewWithBackingStore: instantiator returned 0
Verifying…
Checksumming Protective Master Boot Record (MBR : 0)…
Protective Master Boot Record (MBR :: verified   CRC32 $CE30EE55
Checksumming GPT Header (Primary GPT Header : 1)…
 GPT Header (Primary GPT Header : 1): verified   CRC32 $63C614F0
Checksumming GPT Partition Data (Primary GPT Table : 2)…
GPT Partition Data (Primary GPT Tabl: verified   CRC32 $CF3D593B
Checksumming  (Apple_Free : 3)…
                    (Apple_Free : 3): verified   CRC32 $00000000
Checksumming disk image (Apple_HFS : 4)…
...............................................................................
          disk image (Apple_HFS : 4): verified   CRC32 $EFAEB3C1
Checksumming  (Apple_Free : 5)…
                    (Apple_Free : 5): verified   CRC32 $00000000
Checksumming GPT Partition Data (Backup GPT Table : 6)…
GPT Partition Data (Backup GPT Table: verified   CRC32 $CF3D593B
Checksumming GPT Header (Backup GPT Header : 7)…
  GPT Header (Backup GPT Header : 7): verified   CRC32 $1A757E30
Verification completed…
Error 0 (Undefined error: 0).
verified   CRC32 $B991456E
Attaching…
DI_kextWaitQuiet: about to call IOServiceWaitQuiet...
DI_kextWaitQuiet: IOServiceWaitQuiet took 0.000003 seconds
2021-03-23 15:45:45.013 diskimages-helper[28133:2086659] DIHelperHDID serveImage: attaching drive
{
    autodiskmount = 1;
    "hdiagent-drive-identifier" = "FB80D1D7-13FD-4CBF-B6AE-A0C2C40EB221";
    "unmount-timeout" = 0;
}
2021-03-23 15:45:45.014 diskimages-helper[28133:2086659] DIHelperHDID serveImage: connecting to myDrive 0x3B0B
2021-03-23 15:45:45.014 diskimages-helper[28133:2086659] DIHelperHDID serveImage: register _readBuffer 0x7fac4536a000
2021-03-23 15:45:45.014 diskimages-helper[28133:2086659] DIHelperHDID serveImage: activating drive port 17419
2021-03-23 15:45:45.014 diskimages-helper[28133:2086659] DIHelperHDID serveImage: set cache enabled=TRUE returned SUCCESS.
2021-03-23 15:45:45.014 diskimages-helper[28133:2086659] DIHelperHDID serveImage: set on IO thread=TRUE returned SUCCESS.
2021-03-23 15:45:45.014 diskimages-helper[28133:2086659] -processKernelRequest: will sleep received
Checking volumes…
Volume check completed…
Mounting…
2021-03-23 15:45:46.081 diskimages-helper[28133:2086634] _mountDevEntries: disk4s1 aborting mountpoint postflight because disk image has no band size specified.
2021-03-23 15:45:46.081 diskimages-helper[28133:2086631] _postflightMountPointsAfterDAMount: disk4s1 aborting because disk image has no band size specified.
2021-03-23 15:45:46.082 diskimages-helper[28133:2086631] _postflightMountPointsAfterDAMount: disk4 aborting because no mount point found.
Finishing…
Finishing…
/dev/disk4          	GUID_partition_scheme          	
/dev/disk4s1        	Apple_HFS                      	/Volumes/ResponsivelyApp 0.15.0

**Comment by manojVivek** [comment]
@asitaaa Can you please add more details on when you get this error exactly? 
Please include the environment details and a screenshot of the error as well.

**Comment by asitaaa** [comment]
It started to work only after I installed the Chrome Extension. BTW, it truly is awesome. I can see it being used on a daily basis for my web development.

**Comment by manojVivek** [comment]
Glad it worked! 🎉
