### ISSUE TITLE
Site seems to be down?

### ISSUE THREAD

**Issue by Tiberriver256** [responsively-org/responsively-app#568]
Trying to hit the https://responsively.app website I get the following

![image](https://user-images.githubusercontent.com/6989492/112514409-a8ec2f00-8d6b-11eb-9ac2-af8bfd9e87a3.png)

**Comment by jjavierdguezas** [comment]
I can confirm this @manojVivek

**Comment by Tiberriver256** [comment]
Looks to be back up
