### ISSUE TITLE
New App Icon

### ISSUE THREAD

**Issue by menjilx** [responsively-org/responsively-app#569]
# 🚀 Feature Request
Is it okay if I will design a new "App Icon" for Responsively?

# UI Bug Report
![image](https://user-images.githubusercontent.com/14908836/112810067-42d61380-90ad-11eb-8691-36685293b952.png)

I think it is better to use "Responsively".

:)

**Comment by jjavierdguezas** [comment]
Hi @menjilx thanks for thinking about this. please join us on #357 and talk about your ideas. I'm closing this meanwhile.
