### ISSUE TITLE
Flex Gap

### ISSUE THREAD

**Issue by Trettin** [responsively-org/responsively-app#582]
# 🐞 bug report

### ✍️ Description

The app doesn't support the Gap property from display: flex;
It's the first time i try to report something.
I hope it's ok. 

### 🌍 Your Environment

<pre><code>

</code></pre>

### 🔥 Exception or Error or Screenshot

<pre><code>

</code></pre>

**Comment by jjavierdguezas** [comment]
Hi can you provide a reproducible example?

**Comment by manojVivek** [comment]
I can see that Chrome added support for `gap` property from version 84, but the latest version of Responsively uses version 83. 

Electron version upgrade is the solution for this. 

Ref: https://caniuse.com/?search=gap

**Comment by devinekadeni** [comment]
Hi, is there any update on this one?
Currently it's still there.

My App:
Version: 0.18.0
Electron: 9.3.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 21.1.0

@manojVivek

**Comment by manojVivek** [comment]
@devinekadeni No major progress on this yet. The current code uses of many APIs that are removed in the latest version of electron. So, this required a major revamp of the app.

**Comment by harrytran998** [comment]
Hi @manojVivek, can you update the progress of this issue? Hick, I love this but can not use this BCS this problem.

**Comment by trevorwhealy** [comment]
Just had the same realization debugging Responsively. Our site uses a lot of grid gap and flex gap.

**Comment by hamitaksln** [comment]
I love the application but because of this I cannot use it.

**Comment by 1mzino** [comment]
Any updates? Makes what is a great devtool somewhat less appealing

**Comment by jjavierdguezas** [comment]
This is a known issue and we are tackling it by rewriting the entire app. You can follow the progress on https://github.com/responsively-org/responsively-app/issues/724

Maybe [the alpha release](https://github.com/responsively-org/responsively-app/releases/tag/v1.0.0-alpha.2) will work for you

**Comment by Ruslancic** [comment]
Hey, any news about this issue?

**Comment by manojVivek** [comment]
@Ruslancic This is fixed.

Please get the new version from here, and it should work: https://responsively.app/download/?beta=true
