### ISSUE TITLE
CLI domains with none or one character after . route to about:blank

### ISSUE THREAD

**Issue by cassi10** [responsively-org/responsively-app#608]
# 🐞 bug report

### ✍️ Description

This is on Windows. Not sure about other OS's.

When starting Responsively through CLI command the address `localhost`, `localhost.c`, `google`, `google.a` route to `about:blank` instead.
However, `google.aa` or `localhost.com` go to the specified route.

### 🕵🏼‍♂️ Is this a regression?

Unknown, not tested. I assume this began when the feature to open through CLI was added.

### 🔬 Minimal Reproduction

Open `Powershell` or `cmd`.
Run command `ResponsivelyApp.exe "localhost" or "google" or "google.a"`.
Wait for it to boot.

### 🌍 Your Environment

<pre><code>
Version: 0.17.0
Electron: 9.3.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
</code></pre>

### 🔥 Exception or Error or Screenshot

I see no errors.

### EDIT

I believe the cause of the problem is the isURL [(this line exactly)](https://github.com/responsively-org/responsively-app/blob/dcd77826f5722bc85c113b31c3dde593d85dbb5f/desktop-app/app/main.dev.js#L159) function from the validator module. [It seems](https://github.com/validatorjs/validator.js/issues/754) you need the `require_tld: false` option to allow URL's like `localhost` and `google` to pass.

**Comment by jjavierdguezas** [comment]
Hi @cassi10 

Right now, when responsively is started from CLI, the argument passed is analyzed to check if it is a valid URL or file path. If it is not, then it fallbacks to your startup configuration (blank page or home page). Probably, you have checked blank page for startups, right?
Also, we have a bug checking URLs that it is being addressed in #605. I tested the URLs you provided here, and they work fine, so when that PR is merged this issue should be fixed
Thanks for your report
cc: @manojVivek

**Comment by cassi10** [comment]
Yep, that PR seems to fix this issue. Thanks!
