### ISSUE TITLE
Not taking into account flexgrid gap property.

### ISSUE THREAD

**Issue by Nuno111** [responsively-org/responsively-app#611]
Hi all,

Would just like to report a bug, the app isn't taking into account flex grid gap property , I am using react + tailwind and on chrome, it's displayed properly the gap but when using responsively the grid gap is ignored.

Thank you!

**Comment by Nuno111** [comment]
![image](https://user-images.githubusercontent.com/42497768/124310346-f1ce3380-db63-11eb-9c87-c1a0a06dcd69.png)


as you can see I have the gap property all set up but the app ignores it, it works in my chrome browser fine

**Comment by jjavierdguezas** [comment]
hi @Nuno111 , we are addressing this on #582

**Comment by jeanlambert17** [comment]
This is still happening on mac os with m1

**Comment by LeonTurut** [comment]
Still happening on:
Version: 0.19.0
Electron: 9.3.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by loppam** [comment]
this is still happening

**Comment by Halezis** [comment]
Using Responsively for the first time today on the version, and still the same issue with gap. Is there an alternative way around that?

**Comment by danielseow** [comment]
Having same issue also

**Comment by kwanamari** [comment]
I am experiencing the same issue

**Comment by homoky** [comment]
I have the same issue.

**Comment by gabrielo91** [comment]
Same issue here

**Comment by manojVivek** [comment]
This got fixed in `v1` release of the app, which is in `alpha` right now. You can test it out by downloading binaries here: https://github.com/responsively-org/responsively-app/releases

**Comment by azam4code** [comment]
Still having the same gap property issue.

**Comment by manojVivek** [comment]
@azam4code Can you let us know the version you're using? `Help` menu -> `About` should give the necessary details.

**Comment by azam4code** [comment]
@manojVivek currently I am using Version 1.0.3, and its working fine.

**Comment by azam4code** [comment]
@manojVivek I was using  0.19.1. that was having issues with gap property, and align-items: end.

**Comment by manojVivek** [comment]
Great! 🎉
