### ISSUE TITLE
Apple silicon Support 

### ISSUE THREAD

**Issue by alexander9306** [responsively-org/responsively-app#621]
# 🚀 Feature Request

### 📝 Description

The app is really slow on MacBook Pro 16 GB  with M1

### ✨ Describe the solution you'd like

Electron 11 ships with Apple Silicon support

**Comment by yy523697597** [comment]
I really need the apple silicon native version. The electron  app is really slow via Rosetta2.

**Comment by kudlav** [comment]
Hi, I have MacBook Air (13-inch, Mid 2013) and the app is really slow. Sometimes consumes all the available resources.

**Comment by M4xiGitHub** [comment]
Really looking forward to this 👍

**Comment by ffaubert** [comment]
Is there a plan for this? What is the blocker? What else is needed to get this moving?

**Comment by manojVivek** [comment]
This is fixed in the `v1` beta release. Please download the binary here: https://responsively.app/download/?beta=true
