### ISSUE TITLE
Horizontal Scrollbar on every page

### ISSUE THREAD

**Issue by prashantacharya** [responsively-org/responsively-app#631]
# 🐞 bug report

### ✍️ Description

On every pages, there's a horizontal scrollbar.

#### Screenshot
![image](https://user-images.githubusercontent.com/23692097/136525714-ffaf3115-d930-4c8f-a4dd-56e56aae8430.png)

#### Environment
This issue is identified in Firefox version 92 and Google Chrome version 94.

**Comment by jjavierdguezas** [comment]
closing this as `invalid` as no further information has been given
