### ISSUE TITLE
 NEW TABS IN RESPONSIVELY BROWSER

### ISSUE THREAD

**Issue by VaarunSinha** [responsively-org/responsively-app#637]
# NEW TABS IN RESPONSIVELY BROWSER

### 📝 Description

NEW TABS LIKE A REAL BROWSER

### ✨ Describe the solution you'd like

NO SOLUTIONS

### ✍️ Describe alternatives you've considered

COULD NOT FIND ALTERNATIVE...

**Comment by jjavierdguezas** [comment]
closing this as duplicated of #215
