### ISSUE TITLE
Appearance : Theme - Selection not saved when app is closed.

### ISSUE THREAD

**Issue by sunstarjeff** [responsively-org/responsively-app#644]
User Preferences > Appearance > Theme

Chose "Light Mode".  Selection not saved when app is closed. After a restart of the program, it reverts back to Dark Mode.

# 🐞 bug report

### 🌍 Your Environment

<pre><code>

</code></pre>

### 🔥 Exception or Error or Screenshot

<pre><code>

</code></pre>

**Comment by jjavierdguezas** [comment]
Hi @sunstarjeff I think this is a duplicate of #589
