### ISSUE TITLE
Commandline Parameter --url 

### ISSUE THREAD

**Issue by dboschm** [responsively-org/responsively-app#649]
# 🚀 Feature Request Commandline Parameter --url 
### 📝 Description
To integrate with other development tools (e.g. vs code launch command, automated UI testing etc), it would be great to be have a cli to start the app from powershell/bash/shell opening the specified url.

### ✨ Describe the solution you'd like
`responsivelyapp --url localhost:4200`

**Comment by manojVivek** [comment]
@dboschm You can do that right now by passing the required URL as the first argument to the app binary.

On Mac:
```>/Applications/ResponsivelyApp.app/Contents/MacOS/ResponsivelyApp https://github.com```

On Windows:
```>\path\to\ResponsivelyApp.exe https://github.com```

**Comment by dboschm** [comment]
Thanks for the information. Sorry for opening the Feature Request.
