### ISSUE TITLE
Export/Import config / devices list

### ISSUE THREAD

**Issue by HugoHeneault** [responsively-org/responsively-app#656]
# 🚀 Feature Request

### 📝 Description

Add an export (& import) button allowing to export settings and devices list.
As a team, or if you change computer, it's an easy way to work/ test the same way.

### ✨ Describe the solution you'd like

In the settings view, add an export button, allowing to export defined config as JSON, XML or any format that can later be re-imported in Responsively.

First for your awesome tool! Keep going :)

**Comment by HugoHeneault** [comment]
Hey :)

I'm actually contributing financially but cant' add the priority tag :)

**Comment by jjavierdguezas** [comment]
Hi @HugoHeneault this is a great idea, and thanks for your contributions! 💪🏻

**Comment by danielm2402** [comment]
Hey, I'm working in PR for this, if you like you can assign me

**Comment by manojVivek** [comment]
@danielm2402 Assigned this to you. Thank you, so much. 🚀

**Comment by manojVivek** [comment]
> cc: @manojVivek please take a look at the `priority` tag issue (I couldn't add it either)

@jjavierdguezas Yeah, looks like some bug in the bot? 🤔 
Their repo is archived as well: https://github.com/opencollective/opencollective-bot

**Comment by jjavierdguezas** [comment]
> > cc: @manojVivek please take a look at the `priority` tag issue (I couldn't add it either)
> 
> @jjavierdguezas Yeah, looks like some bug in the bot? 🤔 Their repo is archived as well: https://github.com/opencollective/opencollective-bot

yeah, it seems that the bot is going to be deprecated 😓 (First sentence on: https://github.com/opencollective/opencollective/issues/4006#issuecomment-784212449)

**Comment by danielm2402** [comment]
Could you please review my pull request?  There are some interesting things to discuss there
