### ISSUE TITLE
Not Connected to the Internet

### ISSUE THREAD

**Issue by MVCreativeServices** [responsively-org/responsively-app#663]
# 🐞 bug report

### 🕵🏼‍♂️ Is this a regression?

I can now no longer access Pro features even though I've upgraded. I get an error notice that says I'm not connected to the internet. Even after rebooting the app.

![EQ](https://user-images.githubusercontent.com/30323889/151449757-26ee2a8d-2827-48ff-ab5f-a2f9bacf53ad.jpg)

**Comment by jjavierdguezas** [comment]
I think you are in the wrong repo 😅
