### ISSUE TITLE
Add the ability to remove unwanted devices

### ISSUE THREAD

**Issue by Heatmanofurioso** [responsively-org/responsively-app#670]
# 🚀 Feature Request

### 📝 Description

I'd like to have the possibility to remove devices added in the device manager.

![image](https://user-images.githubusercontent.com/13050270/162308647-23e8612a-e19a-4376-a83a-26da76e73ad1.png)

### ✨ Describe the solution you'd like

Add a garbage or a tin can in the bottom right corner, to drag devices we wish to remove from the list

### ✍️ Describe alternatives you've considered

A button on the specific device to remove.

**Comment by jjavierdguezas** [comment]
Hi @Heatmanofurioso  default devices can't be deleted right now, but custom ones **can**:

![image](https://user-images.githubusercontent.com/13673443/186405176-8aabd1b1-2f1c-40c9-854b-8184d6b827a8.png)

1- Open the Device Manager
2- Move the custom device to the inactive list
3- Hover over the far right of the device card
4- A button to remove the device will appear
