### ISSUE TITLE
App is always launched in Dark mode

### ISSUE THREAD

**Issue by kudlav** [responsively-org/responsively-app#676]
# 🐞 bug report

### ✍️ Description
ResponsivelyApp is always launched in dark mode. When is set Theme to the Light mode, then Close window, and then open new window, the app is back in black. Also quitting the app resets the Theme setting to the dark.

### 🔬 Minimal Reproduction
1. Open app
2. Set Theme to Light
3. Close the window
4. Open new window
5. App is Dark

### 🌍 Your Environment

<pre><code>Version: 0.18.0
Electron: 9.3.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.6.0
</code></pre>
Installed via Homebrew
### 🔥 Exception or Error or Screenshot
No exception nor error

**Comment by PurnenduMIshra129th** [comment]
Hello i have some idea to solve this problem and i must solve this bug .Can you give  Permission please?

**Comment by jjavierdguezas** [comment]
closing this as duplicated of #589 
@B3AST721 @PurnenduMIshra129th please ask there to contribute, thanks!
