### ISSUE TITLE
Everything is broken 😅

### ISSUE THREAD

**Issue by mindplay-dk** [responsively-org/responsively-app#680]
# 🐞 bug report

### ✍️ Description

I apologize in advanced for the poignant title - I don't know how else to describe this.

### 🕵🏼‍♂️ Is this a regression?

Don't know.

It might be related to #449 but maybe not? (my fonts are loading just fine, from localhost or anywhere - I checked the Network tab in Responsively and it appears to be loading and interpreting all resources correctly.)

### 🔬 Minimal Reproduction

Open this in Responsively:

https://1mj5nu.csb.app/

### 🌍 Your Environment

    

Paste what here? Sorry, I don't know what this section is for.

### 🔥 Exception or Error or Screenshot

Here's the page as it renders in Responsively:

![image](https://user-images.githubusercontent.com/103348/168420049-37a64e5a-6ccb-4f7b-8486-e3ac5db7cdb3.png)

It's hard to tell what's going on, but at least containers and backgrounds aren't rendering correctly, and block elements aren't triggering line breaks.

Here we are in Chrome:

![image](https://user-images.githubusercontent.com/103348/168420159-3ce081c5-f1cf-416a-835b-9967367b4bea.png)

Mobile preview in Firefox:

![image](https://user-images.githubusercontent.com/103348/168420242-c1237f27-1341-451c-a17a-c1d07df2c66f.png)

Safari 12:

![image](https://user-images.githubusercontent.com/103348/168420587-2fb14019-50be-4988-a3a4-d31f9abb03b1.png)

Safari 11 on a crusty old iPhone 6:

![image](https://user-images.githubusercontent.com/103348/168420748-717ceae9-c638-49c9-8123-7fc67145aa38.png)

I am **by no means** a CSS expert, but I've been pretty careful about testing my work on older browsers and devices along the way while building this. I'm just targeting browsers up to 2 years old, so I am using things like `flex`, custom properties and data URLs - but nothing much more advanced than that.

Which browser engine does your app use? Just wondering. Whether Chromium or Quantum, it should be fine, assuming it's not a very old build or something. I haven't seen my page rendering like it does in Responsively in any other browser, no matter how old.

And it might not be a browser engine issue. Could have something to do with the way you emulate devices maybe?

Having tested a bunch of other tools similar to Responsively, I did notice my page rendering like this is in [LT Browser](https://www.lambdatest.com/intl/en-dk/lt-browser), so maybe these have something in common? (I suspect that LT Browser may in fact a rebranded/redesigned fork of Responsively, designed to promote LambdaTest? who knows.)

I noticed in DevTools that you inject `browser-sync` into the page - I do that myself when testing from localhost in browsers and devices myself, and that doesn't seem to cause any problems.

Not sure what else I can add to this bug report. I don't think I'm doing anything crazy advanced on this page? Responsively looks like a great tool - but it doesn't render CSS like any browser I know, and therefore sadly not much use as it is.

Please let me know if there's anything else I can do to help you isolate or diagnose the issue?

**Comment by jjavierdguezas** [comment]
Hi, thanks for reporting this

I compared the styles applied on chrome and responsively, and I think the issue here is with the ```display: revert;``` css rule

On Responsively the rule is invalid:
![image](https://user-images.githubusercontent.com/13673443/170008363-f0d65f28-545f-4523-9866-b95512742476.png)


if we change it to, let say, ```display: block;``` it looks just fine:
![image](https://user-images.githubusercontent.com/13673443/170008146-6d27b43c-69ab-4e05-b33c-473007dc2574.png)

This is because the version of [electron currently being used that uses Chromium v83](https://github.com/responsively-org/responsively-app/discussions/679), and it looks like the ```revert``` rule [is supported starting with v84](https://developer.mozilla.org/en-US/docs/Web/CSS/revert#browser_compatibility)
