### ISSUE TITLE
Deleting Cache 

### ISSUE THREAD

**Issue by MVCreativeServices** [responsively-org/responsively-app#691]
# 🐞 bug report

### ✍️ Description

I've been using Responsively for some time. It used to let you clear the cache. The current version doesn't seem to have a way to do so. Refreshing the browser doesn't help. How do I do so? Right now, it only refreshes the cache by quitting & restarting the browser.

### 🕵🏼‍♂️ Is this a regression?

Yes

### 🔬 Minimal Reproduction

Refresh its browser

**Comment by manojVivek** [comment]
@MVCreativeServices This issue is fixed in the latest beta release as part of the app revamp. 

Please check it out here: https://responsively.app/download/?beta=true

Please re-open if this still occurs in the latest beta.
