### ISSUE TITLE
Detect responsively.app so we can tag it as robot traffic

### ISSUE THREAD

**Issue by adriaanvanrossum** [responsively-org/responsively-app#696]
# 🚀 Feature Request

### 📝 Description

We run a analytics company, Simple Analytics, and some customer sees traffic of many browsers when using Responsively.app. This makes sense, but for us there is no way to detect the traffic because the user agents seem to not include the Responsively.app name.

### ✨ Describe the solution you'd like

Some tools define a variable on the window object. For example `window._bot = true`. That would be super helpful.

### ✍️ Describe alternatives you've considered

N/A

**Comment by w4rner** [comment]
as the customer in question, I second this request!
Responsively: please help analytics start-ups with similar open-web values like Simple Analytics be better able to clean data. Your product is phenomenal, but unfortunately has a bot-like effect on analytics.
Thanks!

**Comment by jjavierdguezas** [comment]
should this be configurable or is it enough to set `windows._bot=true`?
cc: @manojVivek

**Comment by adriaanvanrossum** [comment]
Thanks for looking into this.

> should this be configurable or is it enough to set `windows._bot=true`?

If it's configurable, it defeats the whole purpose, I guess.

**Comment by manojVivek** [comment]
A quick suggestion, instead of just `window._bot`, we should name space it with something like `window.responsively_bot=true`? Or if there is some other standard name used by most providers, then we can prefer that.

Just concerned about polluting the user space.

**Comment by adriaanvanrossum** [comment]
> `window.responsively_bot=true`

I would suggest keeping it very short. As an analytics business, we need to keep our code very short. If we need to update and include our scripts every time for a new robot browser, it would be time-consuming and make our script havier. The more general and short the better.

**Comment by adriaanvanrossum** [comment]
Thanks, will monitor the releases:

![2022-07-06-11h14-screenshot](https://user-images.githubusercontent.com/1079135/177515967-58e8a452-c5ca-4c5f-b57e-da07668fead6.png)

If I'm correct I should wait for v0.20.0 to be released, right?

**Comment by w4rner** [comment]
when will the release likely go out?
------- Original Message -------

**Comment by manojVivek** [comment]
It is live now, apologies for the delay.

**Comment by w4rner** [comment]
wahey: congrats! Look forward to start using Responsively again!
While I'm here, can I just ask, is there a feature for previewing what og:images will look like within Responsively? If not can I make that a feature request!
------- Original Message -------

**Comment by manojVivek** [comment]
No, we don't have that feature right now.
