### ISSUE TITLE
Electron is 2 years out of date

### ISSUE THREAD

**Issue by lkhrs** [responsively-org/responsively-app#698]
Hi,

Looks like Responsively uses Electron 9.0.0, which contains Chrome 83. Electron 19.0.0 is the current latest version and contains Chrome 102. Chrome has gained support for several new standards in the last two years, some of which are becoming popular:

- CSS Flexbox/Grid Gap (added in Chrome 84)
- CSS `display: revert`
- CSS Cascade Layers
- AVIF images

[Can I Use comparison between Chrome 83 and 102](https://caniuse.com/?compare=chrome+83,chrome+102&compareCats=all)

My projects use most of these, and the lack of support means I have to use other tools to test responsiveness. Lack of support for Flexbox/Grid Gap causes my layouts to render very differently across screen sizes, for example, and similar for `display: revert` and `@layers`.

**Comment by jjavierdguezas** [comment]
we hope this will be fixed after https://github.com/responsively-org/responsively-app/issues/724

**Comment by jjavierdguezas** [comment]
closing this as duplicated of #456
