### ISSUE TITLE
Ask for contribution

### ISSUE THREAD

**Issue by Sugamlake** [responsively-org/responsively-app#699]
Hello everyone, I would like to be able to contribute to your project, I would love to participate, I hope I can have positive news.
greetings to all

**Comment by jjavierdguezas** [comment]
Hi @Sugamlake thank for wanting to help us. You can search the issues and/or look for the `help wanted`, `good first issue` tags

**Comment by jjavierdguezas** [comment]
closing this, you can open a discussion if you need more information. thanks!
