### ISSUE TITLE
Browser-sync-client errror

### ISSUE THREAD

**Issue by Conanas** [responsively-org/responsively-app#710]
# 🐞 bug report

Getting error message in console

VM403:5 Refused to load the script 'https://localhost:12719/browser-sync/browser-sync-client.js?v=2.26.7' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

Code where error is produced is as follows

![image](https://user-images.githubusercontent.com/61778709/181673992-6d0977ee-c246-47ea-a8e0-cee95782679f.png)

### ✍️ Description

Working on a project and the pages do not load for any of the screens

<img width="966" alt="image" src="https://user-images.githubusercontent.com/61778709/181674148-15bc067d-ba8b-4cbc-bdb6-fa27d8ac7129.png">

Can load other pages such as youtube. My project can be displayed correctly in chrome

**Comment by z0lo13** [comment]
@Conanas your app have csp enabled and it prevents from connecting to localhost:12719, you need to add it address to the exception, however doing so will breach the csp so i would not recomend doing it on production, you should have set the strict csp for some reason.

**Comment by manojVivek** [comment]
Closing this as this can't be fixed.
The app needs browser sync to do the events mirroring, so you'll have to relax the csp to allow this script to load for your development version.

**Comment by manojVivek** [comment]
The fix is live on v1.3.0, please let me know if you still face the issue after the upgrade.
