### ISSUE TITLE
TailwindCSS prose doens't get pick up

### ISSUE THREAD

**Issue by azzamsa** [responsively-org/responsively-app#715]
# 🐞 bug report

### ✍️ Description

TailwindCSS `prose` class doesn't get pickup.

### 🔬 Minimal Reproduction

1. go to https://deploy-preview-5--azzamsa.netlify.app/
2. compare the result with normal browser

### 🌍 Your Environment

<pre><code>
Version: 0.19.1
Electron: 9.3.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.10.0-17-amd64
</code></pre>

### 🔥 Exception or Error or Screenshot

Responsively:

![image](https://user-images.githubusercontent.com/17734314/187010360-9a6e2ed2-f359-4e23-a468-5794bd4817ec.png)

![image](https://user-images.githubusercontent.com/17734314/187010363-21d8234b-7229-4638-8b76-c3a824efeacc.png)

Normal Browser:

![image](https://user-images.githubusercontent.com/17734314/187010411-dda32bbe-c162-408c-ac31-dedf87850fa5.png)

![image](https://user-images.githubusercontent.com/17734314/187010451-5d6b89c9-ca90-4f9c-a95e-bf165f33d8e0.png)

**Comment by manojVivek** [comment]
@azzamsa This is because of the outdated browser engine in the old app, this should work in the latest beta release of the revamped app.

Check it out here: https://responsively.app/download/?beta=true

Please re-open if this doesn't work in the latest beta too.
