### ISSUE TITLE
Chocolatey package is outdated

### ISSUE THREAD

**Issue by soredake** [responsively-org/responsively-app#721]
Chocolatey package is outdated (0.17.0 version), please update it to latest version.

**Comment by diegoherrer4** [comment]
I'd love to help with this issue.

**Comment by jjavierdguezas** [comment]
The updated version was submitted: https://community.chocolatey.org/packages/responsively/0.19.1
It is Pending automated review

**Comment by jjavierdguezas** [comment]
Closing this as All Checks are Passing
