### ISSUE TITLE
the app did not support gap property

### ISSUE THREAD

**Issue by abdenassar01** [responsively-org/responsively-app#726]
# 🚀 Feature Request

### 📝 Description

I use grid and flex heavily in my design. So I rely on gap to add spacing between my boxes and the problem is that responsively does not support css gap property so I find my self going back between chrome and responsively just to see if everything works as expected.

I would appreciate If you just code make it work. because  that well give me the possibility to only test in responsively and stick with it for the development process.  

### ✨ Describe the solution you'd like

I don't have any idea how responsively is made or is it rely on a third party css processor but I hope the community could find a way to make it right and fix this bag.

### ✍️ Describe alternatives you've considered

I could get around it using padding and the like but I prefer css gap for its flexibility.

**Comment by tomoyanime** [comment]
@abdenassar01 It's due to the Chrome version (83) this app uses. It will be fixed once the maintainer updates the app. #720

**Comment by jjavierdguezas** [comment]
closing this as duplicated, we hope this will be fixed after #724
