### ISSUE TITLE
Elementor Weird Spacing

### ISSUE THREAD

**Issue by cmasonuk** [responsively-org/responsively-app#738]
Hi new to the app, but love it, fantastic and thank you : )

Using Elementor however, noticed the app seems to ignore spacing set by Elementor for certain widgets etc.

For example:

![Screenshot 2022-10-23 at 18 04 09](https://user-images.githubusercontent.com/116509922/197405449-82c09a29-2143-4015-acd4-fe5e9cd32777.png)

Should look like this:

![Screenshot 2022-10-23 at 18 04 24](https://user-images.githubusercontent.com/116509922/197405474-99a06309-52c3-4a3e-983a-50db0ea1e3f6.png)

**Comment by manojVivek** [comment]
@cmasonuk This is a known problem tracked in #698. And it got fixed in `v1` of the app, which is in `alpha` right now.

You can use the alpha app from here: https://github.com/responsively-org/responsively-app/releases/tag/v1.0.0-alpha.2

Please let us know if you still find this still a problem in `v1`.

**Comment by manojVivek** [comment]
You can check the assets section of a release to get the download links. 

But here are the download links: 
M1 Mac: https://github.com/responsively-org/responsively-app/releases/download/v1.0.0-alpha.2/ResponsivelyApp-1.0.0-alpha.2-arm64.dmg
Intel Mac: https://github.com/responsively-org/responsively-app/releases/download/v1.0.0-alpha.2/ResponsivelyApp-1.0.0-alpha.2.dmg

**Comment by cmasonuk** [comment]
Thank you, that's a massive help : )

Never used Alpha or Beta software. Can I please ask - will this update and become the standard version, in time?

Or will I need to install a newer version, in the future?

Appreciate it 👍



-- Kind regards, Chris Mason · 01995 608977 · 07761 487918

________________________________

**Comment by manojVivek** [comment]
It should get auto-upgraded to a stable version when it gets released. But I have not tested that yet to be 100% sure. :)

**Comment by cmasonuk** [comment]
No worries will report back on anything. Liking the new interface, totally new and streamlined, and the spacing is sorted 🙂👍



-- Kind regards, Chris Mason · 01995 608977 · 07761 487918

________________________________
