### ISSUE TITLE
Support url drag and drop into window

### ISSUE THREAD

**Issue by hobyvh** [responsively-org/responsively-app#743]
# 🚀 Feature Request

### 📝 Description

Support url drag and drop into the main window from other apps

### ✨ Describe the solution you'd like

When I drag a url from another app into the browser window, switch to that url.

### ✍️ Describe alternatives you've considered

Copying and pasting
Dragging into address bar and deleting the previous url then hitting return

**Comment by ParamBirje** [comment]
hey @manojVivek , 

Would you please let me know how you want this feature implemented? Should the selected URL be dropped directly in the App view as in whole, or should the drop area be only limited to the URL bar.

Drag zone in URL bar:
![DropZoneUrlBar](https://github.com/responsively-org/responsively-app/assets/87022870/88833894-35a5-43cf-99b8-59b256341329)

Drag zone on the entire screen:
![DropZoneEntireScreen](https://github.com/responsively-org/responsively-app/assets/87022870/f9d3a024-767f-4615-948f-a6367a85ae6e)

Let me know if any tweaks are needed.

**Comment by manojVivek** [comment]
@ParamBirje Limiting the drag zone only to the URL bar makes more sense as that wouldn't block any drop interaction to the previewed pages.

**Comment by hobyvh** [comment]
Hi,

Yes, I'd prefer the entire screen to be the drop zone. Thanks!

Hoby
