### ISSUE TITLE
Images with absolute positioning invisible

### ISSUE THREAD

**Issue by hobyvh** [responsively-org/responsively-app#744]
# 🐞 bug report

### ✍️ Description

On a site that lays out images in frames with absolute positioning, the images don't display.

They do display in Chrome and other browsers.

### 🕵🏼‍♂️ Is this a regression?

Don't know. I'm a new user.

### 🔬 Minimal Reproduction

1. Go to this page https://seismic.com/blog/
2. See that all the article images don't appear in the page (should be above green box text).
3. To see which images should be displaying: Open dev tools > elements dig down to an article image, disable position (and translate).

### 🌍 Your Environment

<pre><code>

</code></pre>

### 🔥 Exception or Error or Screenshot

<pre><code>

</code></pre>

**Comment by jjavierdguezas** [comment]
Hi, @hobyvh this is related to the css property `aspect-ratio` used in `<img />` tags

![image](https://user-images.githubusercontent.com/13673443/198547574-594b82f0-b6d6-4483-af00-e071309ce836.png)

`aspect-ratio` needs [at least Chrome v88](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio) but Responsively uses electron `9.3.1` so it use chromium version ~[83](https://www.electronjs.org/blog/electron-9-0) (83.0.4103.122 [according to this package](https://github.com/Kilian/electron-to-chromium/blob/9eaf581b7594cf70d41e36b29ba9c66441518e77/full-chromium-versions.js#L848))

This is a known issue and we are tackling it by rewriting the entire app. You can follow the progess on #724

**Comment by jjavierdguezas** [comment]
duplicated of #642
