### ISSUE TITLE
401 Authorization Required on website

### ISSUE THREAD

**Issue by awakekat** [responsively-org/responsively-app#766]
# 🚀 Feature Request

### ✨ In the previous version of Responsively that I just deleted (darn it), allowed for a protected folder on a website that required a username and password on it. 

Now with the new Beta version I just downloaded, I get no prompt for the username and password to load the site but a 401 Authorization Required and the site does not load.

### ✍️ Describe alternatives you've considered

No alternatives at this time, but going to delete this new Beta version and search Setapp for an alternative if there is one or in the app store.

**Comment by manojVivek** [comment]
Thanks for reporting it, will be included in the next release.
