### ISSUE TITLE
Vertically Stacked Devices?

### ISSUE THREAD

**Issue by rvdh70** [responsively-org/responsively-app#773]
Hi RR-devs,

Thanks for developing Responsively App! I just downloaded the latest version, and it looks great. However,  is there no way to 'stack' devices anymore? If I have more than 3-4 devices, I must scroll to the right to see those devices. In the older version, I could scroll down, which I prefer. 

Am I missing a setting, maybe?

Thanks.

Roland

**Comment by manojVivek** [comment]
Taken care of in #770, will go live in the next release.
