### ISSUE TITLE
CSS aspect-ratio is unknown

### ISSUE THREAD

**Issue by Omri-Lvy** [responsively-org/responsively-app#783]
# 🚀 Feature Request

The aspect-ratio CSS property is unknown and thus responsively messes some of the website images and divs

<img width="1096" alt="Untitled" src="https://user-images.githubusercontent.com/79089193/210163550-1bf01241-e902-4f88-847a-2df9c94aa526.png">

**Comment by manojVivek** [comment]
Hi Omry, this is a problem with the old version of the app, can you try the newer app(in beta phase, right now) here: https://responsively.app/download/?beta=true

Please re-open if you face the same problem in the new version as well.
