### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by benharvie** [responsively-org/responsively-app#785]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@a1ise) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by manojVivek** [comment]
Done, taken care of in this https://github.com/responsively-org/responsively-app/commit/738ad442d6c14de793a94a96c9f1cfaa79b34e3d
