### ISSUE TITLE
Device manager background not fitting to screen size

### ISSUE THREAD

**Issue by roidsaja** [responsively-org/responsively-app#786]
# 🐞 bug report

### ✍️ Description

I am using it on my m1 machine with the 1.0.0-beta.5 version. This applies to both light and dark theme.

### 🕵🏼‍♂️ Is this a regression?

Not sure since I have not used the previous version.

### 🔬 Minimal Reproduction

Install the Apple Silicon Beta version and run it.

### 🔥 Exception or Error or Screenshot

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/22772929/213346807-9fa6ae7d-ea51-4cae-8056-140e676a8abf.png">

**Comment by manojVivek** [comment]
@roidsaja Thanks for raising this, the fix will go with the next release.
