### ISSUE TITLE
Can't open local html document which I'm working on to see the preview

### ISSUE THREAD

**Issue by smdsayeed** [responsively-org/responsively-app#795]
# 🐞 bug report
Can't open the local file 
### ✍️ Description
Can't open a local file ( html file ) in the responsively app

when I copied the path of the file and pasted in the responsively app , it is showing some other link 
This issue was not on the previous version
### 🕵🏼‍♂️ Is this a regression?

yes
### 🔬 Minimal Reproduction

Try a copying a local html file path and pasting it in the Application
### 🌍 Your Environment

<pre><code>

</code></pre>

### 🔥 Exception or Error or Screenshot

![responsivley-issue](https://user-images.githubusercontent.com/96527307/215307706-10e5e8fd-c724-40f2-b722-c1019b81c142.jpeg)

<pre><code>

</code></pre>

**Comment by manojVivek** [comment]
@smdsayeed  I just tested this on macOS and it worked. 

Can you try adding `file:///` to the file path like `file:///C:/..`?

**Comment by smdsayeed** [comment]
Tried , showing error 404
![screenshot-1675085803644](https://user-images.githubusercontent.com/96527307/215492263-229a3e5c-c950-4205-9885-9c9ccf9b94e8.jpeg)

**Comment by smdsayeed** [comment]
i didn't add up those %22 it s just showing on the error page

**Comment by smdsayeed** [comment]
> @smdsayeed I just tested this on macOS and it worked.
> 
> Can you try adding `file:///` to the file path like `file:///C:/..`?

not working on windows

**Comment by smdsayeed** [comment]
actually it is showing this error repeatedly
ERROR:-105
ERR_NAME_NOT_RESOLVED

**Comment by manojVivek** [comment]
@smdsayeed  This error definitely indicates that there is an error in the URL. 

Can you try if this URL is working on Google Chrome?

**Comment by smdsayeed** [comment]
It is working on the chrome normally
![test-sending](https://user-images.githubusercontent.com/96527307/215758155-6b32f498-baf9-4682-828b-2d71d517bc98.png)

**Comment by manojVivek** [comment]
I just tried it on a VM on AWS and appending `file:///`  worked for me: 

<img width="968" alt="Screenshot 2023-01-31 at 6 39 04 PM" src="https://user-images.githubusercontent.com/1283424/215768643-f4cb5ce4-264d-4fff-af5d-a7989343e025.png">

**Comment by manojVivek** [comment]
Please reopen with details if the above doesn't work for you.

**Comment by smdsayeed** [comment]
![image](https://user-images.githubusercontent.com/96527307/221842177-d1f1473d-cf7e-4699-a1a4-33328c8d439c.png)

Now it works..!
when appended with the file:///
it doesn't works while there was https 😆
suggestion: can you guys make it work like in it does in chrome , so that i wouldn't need to always write file:///
