### ISSUE TITLE
error 105

### ISSUE THREAD

**Issue by besiedge** [responsively-org/responsively-app#799]
🐞 bug report

✍️ Description
have some problems with using 

 🌍 Your Environment windows 10

🔥 Exception or Error or Screenshot

![image](https://user-images.githubusercontent.com/124689788/217255046-bb97ba4a-ccf9-4b0b-ad76-8e5ed53a1b32.png)

**Comment by manojVivek** [comment]
The address should be `https://google.com` and not `https://google`. 😄
