### ISSUE TITLE
auth is a blocking issue

### ISSUE THREAD

**Issue by jpyrat** [responsively-org/responsively-app#800]
# 🐞 bug report

### ✍️ Description

I have granted access with Github to https://auth.responsively.app/authenticate-app

It displays : 
Login Successful!
You have successfully signed into your account. You can now proceed to use the app!

[Open Responsively App](responsively://user-auth.app.responsively.app/?data=averylongdata)

And nothing appens.

⇒ I can't use the app

### 🕵🏼‍♂️ Is this a regression?

First version with auth (but why in the Hell do you need auth ?)

### 🔬 Minimal Reproduction

See description

### 🌍 Your Environment

Win 11 H2

**Comment by manojVivek** [comment]
This is fixed, can you please redownload the binary and try again?

**Comment by jpyrat** [comment]
Thx, now, it works. 
But did not kept my settings from 0.19 to 1.0.1 :(

**Comment by manojVivek** [comment]
Yes, sorry, v1 is a complete rewrite, and it doesn't work with the old settings.
