### ISSUE TITLE
Must be login when use v1.0.x !!! Why?

### ISSUE THREAD

**Issue by datverse** [responsively-org/responsively-app#803]
Hi, 
Why must be login when use new stable version v1.0.x? No cancel button?
Thanks

**Comment by datverse** [comment]
What happen after I login? My data will be? 
Why lost and benefit for the login? 
Why this login need for this new version?

**Comment by manojVivek** [comment]
Login is introduced as a first step towards introducing account-based solutions like preferences syncing across installations and some proprietary features in the future.

The data will be only used within the Responsively App and not anywhere outside of it.
But here is the privacy policy for in-depth details: https://responsively.app/privacy-policy/

**Comment by datverse** [comment]
No privacy and policy before create account and login.
No accept or cancel.
No account management on new version of app. We can not see "the preferences syncing across inhalations"?
What "introduced as a first step" after created account and login? We don't see this?
How about we just need use the app, we don't need sync any preferences and give you data?
Thanks

**Comment by manojVivek** [comment]
> How about we just need use the app, we don't need sync any preferences and don't want give you any our data?

Sure, point taken. We'll make the login optional in the future release.

**Comment by datverse** [comment]
Please understand and clear this. This is a serious matter. 
On the previous version we use your app don't need provide any data, don't need create account, don't need login. 
Where the option "Cancel / NO" create account and login?

**Comment by datverse** [comment]
Thanks ❤️

**Comment by manojVivek** [comment]
Fixed in v1.0.2.
