### ISSUE TITLE
White screen when I open updated app

### ISSUE THREAD

**Issue by tlanettepollard** [responsively-org/responsively-app#805]
# 🐞 bug report

### ✍️ Description
Hi. When I open the app all I get is a white screen. 

### 🕵🏼‍♂️ Is this a regression?
This did not happen with the old version. I was using Responsively on Friday. When I turned on my computer Saturday, it was updated and not working. I logged into the app using my GitHub login. Once that went through, the app opened to a blank screen. 

### 🔬 Minimal Reproduction
I have uploaded a picture of the screen I see when I open the app. 

### 🌍 Your Environment
I'm working on MacBook Pro 2016 Apple M1 Max with the Ventura 13.1 operating system.

<pre><code>

</code></pre>

### 🔥 Exception or Error or Screenshot
Screen shot uploaded
<pre><code>

</code></pre>
<img width="864" alt="Screenshot 2023-02-11 at 12 15 19 PM" src="https://user-images.githubusercontent.com/25272108/218323716-de287a7c-b177-4cd7-95ad-734e7de38d96.png">

**Comment by manojVivek** [comment]
@tlanettepollard We made some potential fixes on `v1.0.3`. Can you please give that a try and let us know if it still breaks? 

Link: https://responsively.app/download/

**Comment by tlanettepollard** [comment]
Hi I downloaded the updated version. I still have the white screen.

**Comment by manojVivek** [comment]
Hi Trista, we'll definitely get this fixed for you. 
Just that it's trickier to understand what the problem without knowing the logs, so I have uploaded builds with debugging enabled that will help us know what's the error.

Can you please download the following and run it:

Apple Silicon Mac: https://github.com/responsively-org/responsively-app-releases/releases/download/v1.0.3/ResponsivelyApp-1.0.3-arm-debug.app.zip
Intel Mac: https://github.com/responsively-org/responsively-app-releases/releases/download/v1.0.3/ResponsivelyApp-1.0.3-intel-debug.app.zip

After opening the app when you see the blank page, can you `Right click` -> `Inspect Element` and check if there are any errors in the console?

**Comment by tlanettepollard** [comment]
Ok. I will run this when I get home from work today (I’m a teacher). Trista L. PollardOn Feb 28, 2023, at 11:08 PM, Manoj Vivek ***@***.***> wrote:﻿
Hi Trista, we'll definitely get this fixed for you.
Just that it's trickier to understand what the problem without knowing the logs, so I have uploaded builds with debugging enabled that will help us know what's the error.
Can you please download the following and run it:
Apple Silicon Mac: https://github.com/responsively-org/responsively-app-releases/releases/download/v1.0.3/ResponsivelyApp-1.0.3-arm-debug.app.zip
Intel Mac: https://github.com/responsively-org/responsively-app-releases/releases/download/v1.0.3/ResponsivelyApp-1.0.3-intel-debug.app.zip
After opening the app when you see the blank page, can you Right click -> Inspect Element and check if there are any errors in the console?

**Comment by manojVivek** [comment]
I think, this is apple's gatekeeping, as I built these debug binaries in my local. 
Can you try right-clicking the app file and selecting `open`?

**Comment by tlanettepollard** [comment]
> I think, this is apple's gatekeeping, as I built these debug binaries in my local.
> Can you try right-clicking the app file and selecting `open`?

I will try again after work.

**Comment by tlanettepollard** [comment]
Hi. I deleted the app, updated my computer to Ventura 13.2.1. When I downloaded the Intel version of the app for Mac, it finally worked. Thank you for your help.

**Comment by manojVivek** [comment]
Glad to know it worked! 

To keep the app updated with the future releases, please replace the debug build with the latest version here: https://responsively.app/download/
