### ISSUE TITLE
Version 1.0.1 is installed as 1.0.0-beta.6 on Windows

### ISSUE THREAD

**Issue by mriamnobody** [responsively-org/responsively-app#807]
I previously had version 0.19.1 installed on my Windows 11. When I updated Responsively by downloading `ResponsivelyApp-Setup-1.0.1.exe` from the `Releases` section, it was installed as `v1.0.0-beta.6`. You can also check the version in `Programs and Features` in `Control Panel`. 

Also, in the current release 1.0.1, there is no option to check the version of the app.

**Comment by mriamnobody** [comment]
<img width="620" alt="Screenshot (2105)" src="https://user-images.githubusercontent.com/14347205/218353355-f0b5a883-b433-42f1-9d13-365f3d8c1117.png">

**Comment by eigenstil** [comment]
I can confirm this.
<img width="539" alt="image" src="https://user-images.githubusercontent.com/37832701/218476298-785e719a-a00b-4231-8ac9-86393b0e07f6.png">

**Comment by manojVivek** [comment]
Yes, the version discrepancy will be fixed in the next release.

**Comment by mriamnobody** [comment]
@manojVivek Shall I create a new issue for "Also, in the current release 1.0.1, there is no option to check the version of the app."?

**Comment by manojVivek** [comment]
@mriamnobody Yes, please. That would be much appreciated for tracking.

**Comment by manojVivek** [comment]
This is fixed in v1.0.2.
