### ISSUE TITLE
"Dock DevTools" not working when right clicking --> Inspect

### ISSUE THREAD

**Issue by eigenstil** [responsively-org/responsively-app#809]
# 🐞 bug report

### ✍️ Description

DevTools are not docked, even though the option is checked.
<img width="238" alt="image" src="https://user-images.githubusercontent.com/37832701/218472057-e8417401-21b3-4fa8-8e36-e8430c7b6ced.png">

### 🕵🏼‍♂️ Is this a regression?

Yes

### 🔬 Minimal Reproduction

* Check "Dock DevTools" in the settings
* Right click somewhere on an element in the device previews.
* DevTools opens in a seperate window :-(
* Check this screencast to see what I mean: https://share.vidyard.com/watch/1MioFUsK7WveTe1tRuJB6w

### 🌍 Your Environment

<pre>`Ctrl/Cmd + F1` doesn't work for me, very sorry</pre>
* Windows 11
* Responsively App Version 1.0.1

### 🔥 Exception or Error or Screenshot

I did a quick screencast to show what I mean: https://share.vidyard.com/watch/1MioFUsK7WveTe1tRuJB6w

**Comment by manojVivek** [comment]
Thanks for reporting this, did you try re-opening the app and it still didn't work?

**Comment by manojVivek** [comment]
Yes, I can confirm this is a bug. 
As a workaround until this is fixed, you can use the global inspector to open the dev tools and that works as per the option selected:


https://user-images.githubusercontent.com/1283424/218494797-a183ef45-0d1a-49a6-93fe-c9602d249f78.mov

**Comment by manojVivek** [comment]
Fixed in v1.0.2.
