### ISSUE TITLE
Add shortcut for opening dev tools

### ISSUE THREAD

**Issue by manojVivek** [responsively-org/responsively-app#812]
### Discussed in https://github.com/responsively-org/responsively-app/discussions/811

<div type='discussions-op-text'>

<sup>Originally posted by **dev-song** February 17, 2023</sup>
I'm using macOS Ventura 13.1... (Intel Mac)
Is there a shortcut for `Inspect Element` or opening a dev tool?
I'd be much better if I can check elements without moving mouse cursor to top-right of the app everytime...</div>

**Comment by ahmarammar** [comment]
Hey, @manojVivek I hope you are doing well, I think you are looking for shortcuts that help you to open developer tools in your macOS.
1 - Command+Option+C  (It will open the Developer Tools and highlight the element you clicked on)
2 - Command+Option+I (It will open the Developer Tools)

**Comment by Ayan-Kumar-Saha** [comment]
Hi @manojVivek Yes there is a shortcut. Use `Command + Option + I` to open the dev tool.

**Comment by BrijenMakwana** [comment]
Can you please assign this to me? I would love to work on it.

**Comment by EvokerKing** [comment]
Quick suggestion for this: do something like Polypane does where if you hold down alt, it switches to inspect element mode and switches back when you release alt.
