### ISSUE TITLE
No About section under Help tab

### ISSUE THREAD

**Issue by mriamnobody** [responsively-org/responsively-app#813]
# 🚀 Feature Request

### 📝 Description

In the current stable release v1.0.1, there is no 'About' section available within the app.

### ✍️ Describe alternatives you've considered

Adding an 'About' section under the 'Help' tab would be highly beneficial. it was available in the previous version I used, `v0.19.1`.

**Comment by manojVivek** [comment]
Fixed in v1.0.2.

**Comment by eigenstil** [comment]
In the current **windows release** there is still no option for the "About" section:
<img width="184" alt="image" src="https://user-images.githubusercontent.com/37832701/220178937-f544c60d-a4ad-41a8-a406-3b8bfaa382e6.png">
(I downloaded the windows installer about 3 minutes ago from https://responsively.app/download )

**Comment by manojVivek** [comment]
My bad, this is fixed in `v1.0.3` patch release.
