### ISSUE TITLE
Save Zoom Level Preference

### ISSUE THREAD

**Issue by JoelEadeDesign** [responsively-org/responsively-app#841]
Hiya,

When I open ResponsivelyApp, the zoom defaults to 56% which I then increase to 100%. Is there any chance the zoom setting from the previous session can be remembered in the user preferences?

**Comment by manojVivek** [comment]
HI @JoelEadeDesign, I have already fixed this on https://github.com/responsively-org/responsively-app/issues/804

It'll go live in the next release.
