### ISSUE TITLE
post-install script is not working in windows

### ISSUE THREAD

**Issue by codewithmitesh** [responsively-org/responsively-app#859]
# 🐞 bug report

### ✍️ Description

`post-install` script is currently not functioning on the Windows operating system. In particular, the fourth command that starts with "replace-in-file" is not working and is displaying an error message of "The system cannot find the file specified," even though the file location is accurate.

### 🔬 Minimal Reproduction

1. use Windows OS
2. clone main branch
3. go to  desktop-app
4. run command: yarn

### 🌍 Your Environment
<pre><code>
OS: Windows x64
Node: 19.3.0
Electron: 23.1.3
</code></pre>

### 🔥 Exception or Error or Screenshot

<pre>
<img src="https://i.ibb.co/0Bbg7SK/post-install-isssue.png" alt="Issue-Reponsively-Bug" border="0" />
</pre>

**Comment by manojVivek** [comment]
@codewithmitesh Can you please verify if you fix on #858, resolves this?

**Comment by NarrowCode** [comment]
I believe the issue on Windows mostly stems from the fact that a complex command is used in `postinstall`, particularly the section that does the `replace-in-file`.

Windows requires a different escape sequence for angled brackets (supposedly `^` or `^^^`) - so the command is not parsed correctly (it parses `replace-in-file '/// <'` ... and falls apart on the angle bracket).

For cross-platform interoperability it would probably be best to split the `postinstall` step into multiple stages and run the `replace` and `replace-in-file` commands from within a separate TS file, which would also increase general readability.

**Comment by codewithmitesh** [comment]
@manojVivek  No, there is still an issue with the fourth command that begins with `replace-in-file`.

**Comment by manojVivek** [comment]
@NarrowCode  Yeah, I agree, splitting the post-install into multiple steps would be ideal. 

@codewithmitesh Thanks for the investigation and the fixes so far. I'll take a closer look and make a fix for this.
