### ISSUE TITLE
Left menu bar not showing on Windows 11 and 3k resolution

### ISSUE THREAD

**Issue by huqedato** [responsively-org/responsively-app#880]
Left menu bar not showing on Windows 11 and 3000x2000 resolution notebook (HP Spectre x360)
Instead on my other notebook (1920x1080) it appears.
Version 1.1.0
![image](https://user-images.githubusercontent.com/96745833/229290349-90bc8e2a-2404-41f9-87b1-8f66b1708fd2.png)

**Comment by huqedato** [comment]
@manojVivek, this :
![image](https://user-images.githubusercontent.com/96745833/229293754-50ffe203-035a-4ddc-918c-39481804b699.png)

**Comment by manojVivek** [comment]
This sidebar is from the 0.x version of the app and its removed in the v1.x releases. 

Is there any specific use case you're looking for from the sidebar in the new version? 

Also you should upgrade your other installation to the latest, the v0.x app is outdated and buggy with rendering some newer css clauses.

**Comment by huqedato** [comment]
So it's a feature, not a bug! 😄 Cool.

Indeed, in the x0.19x there were lots of useful features/settings such as: devices filtering, app's preferences, extensions, proxy etc.

It's a pity these are missing in the v1 revamp.

I'll install the previous version in my new notebook.
