### ISSUE TITLE
Add `Individual` preview mode

### ISSUE THREAD

**Issue by manojVivek** [responsively-org/responsively-app#883]
### Discussed in https://github.com/responsively-org/responsively-app/discussions/882

<div type='discussions-op-text'>

<sup>Originally posted by **vmind** April  3, 2023</sup>
On previous versions I have 3 layouts to choose.
I always use individual when set custom breakpoints in project on small screens like laptop.
How can I enable it back ? It was very helpful.</div>

**Comment by manojVivek** [comment]
An example of how the individual mode can look is here: https://responsively-org.github.io/responsively-app/assets/video/customizable-layouts.mp4

We can have an icon near the device name to switch to the individual mode.

**Comment by themohammadsa** [comment]
Hey @manojVivek, I would like to pick up this issue. This would be my first FOSS attempt, have already setup the necessary stuff. Let me give this a shot.

**Comment by manojVivek** [comment]
@themohammadsa Please go for it!

**Comment by themohammadsa** [comment]
Hey @manojVivek, I am attaching the PR for this issue below. Let me know the changes required.

https://github.com/responsively-org/responsively-app/pull/944
