### ISSUE TITLE
Ability to Rotate Only One Device, Not All at Once.

### ISSUE THREAD

**Issue by DanielFirpo** [responsively-org/responsively-app#897]
# 🚀 Feature Request

### 📝 Description

Right now you can only rotate all devices all at once.

### ✨ Describe the solution you'd like

It would be nice to be able to rotate them individually.

### ✍️ Describe alternatives you've considered

Right now I just add a custom device and mirror the dimensions of the device I'm working on, that way I always have for example the iPhone 12 Pro, and then a custom device which is just the iPhone 12 Pro with landscape dimensions. This is kinda clunky though.

**Comment by prabhjotsingh18** [comment]
Hey Team, 

I would like to work on this feature request.

**Comment by manojVivek** [comment]
@prabhjotsingh18 Sorry,based on the communication on Discord it's already been picked up. 

Please look for other issues.

**Comment by kenzaOut16** [comment]
Hello, 
I want to check if there are any updates on the progress of this. Also, I was wondering if there is an active branch related to this feature request that I could check out.

If the feature request has not been assigned to anyone yet, I would like to express my interest in working on it. Please let me know if it's still available, and I'll be happy to take it on.

**Comment by manojVivek** [comment]
@kenzaOut16 Thanks for your interest. Can you please join our Discord and give a ping on the previous discussion on this here: https://discord.com/channels/992277343408246825/992278054682497035/1097568207637844098

**Comment by manojVivek** [comment]
This feature is live on v1.3.0, please let me know if you have any feedback after the upgrade.
