### ISSUE TITLE
CMD+R shortcut does not refresh (MacOS)

### ISSUE THREAD

**Issue by SHxKM** [responsively-org/responsively-app#909]
# 🐞 bug report

This app is awesome.

### ✍️ Description

Since hot-reloading doesn't seem to be a feature I'll need a quick way to refresh the page. On MacOS, hitting `CMD+R` shortcut does not cause a page refresh (MacOS).

### 🕵🏼‍♂️ Is this a regression?

I don't know.

### 🔬 Minimal Reproduction

Hit `CMD+R`

### 🌍 Your Environment

<pre>Apple M1, MacOS 13.0 (22A380)<code>

**Comment by SHxKM** [comment]
False alarm. A restart helped.

**Comment by DanInProgress** [comment]
As a corellary, I noticed a similar behavior when switching to/from columnar layout. Only restarting helped.

Adding a note as it might help someone else :)
