### ISSUE TITLE
Add bookmarks functionality

### ISSUE THREAD

**Issue by manojVivek** [responsively-org/responsively-app#916]

**Comment by Agastya18** [comment]
hey @manojVivek  can you explain more about this issue

**Comment by prabhjotsingh18** [comment]
from what I'm guessing is to add a browser bookmark bar to the app.

**Comment by manojVivek** [comment]
Bookmark bar would be become a clutter on small screens, and I'm thinking something like this to the dropdown settings. 

Also, we can have a similar `star` icon to the address bar as well. 

<img width="839" alt="Screenshot 2023-05-09 at 4 59 47 PM" src="https://github.com/responsively-org/responsively-app/assets/1283424/b634abd1-aff9-4bff-9e1b-61596d137f60">
