### ISSUE TITLE
When running all devices  iphone 6/7/8 doesnt load

### ISSUE THREAD

**Issue by agustif** [responsively-org/responsively-app#92]
Maybe this is understandable but it would be a nicee to hhave, at 10% I can see all viewports/devices in one quick view

**Comment by agustif** [comment]
After closing most of other apps (chrome etcc) it works but iphone 6/7/8 will keep stuck won/t load...

Any ideas why?

**Comment by manojVivek** [comment]
@agustif `iphone 6/7/8` getting stuck could be some special case with the page that you tested it with. 

Can you let us know the details like the URL and the actions you did to produce it? So that we can reproduce it to find the root cause.
