### ISSUE TITLE
Not showing the name of icons

### ISSUE THREAD

**Issue by Agastya18** [responsively-org/responsively-app#921]

**Comment by manojVivek** [comment]
@Agastya18 We show the native tooltip if you hover over the toolbar icons for more than a sec liek below:

<img width="291" alt="Screenshot 2023-05-09 at 2 34 01 PM" src="https://user-images.githubusercontent.com/1283424/237048515-c51cb4ce-8ed0-4be1-b801-0b9c5f713f3d.png">


Did you mean something else?

**Comment by Agastya18** [comment]
thanks
