### ISSUE TITLE
[FR] Ability to edit device name

### ISSUE THREAD

**Issue by KnifeFed** [responsively-org/responsively-app#922]
# 🚀 Feature Request

### 📝 Description

After creating a custom device, you can't edit the device name.

### ✨ Describe the solution you'd like

You should be able to edit the device name.

**Comment by WayneRocha** [comment]
@manojVivek Can I handle with that Issue this week?

**Comment by manojVivek** [comment]
@WayneRocha That would be fantastic! ♥️

**Comment by utkarsh-shrivastav77** [comment]
Hi is this issue still open

**Comment by manojVivek** [comment]
@utkarsh-shrivastav77 I guess Wayne will be taking care of this. 

If you're interested, https://github.com/responsively-org/responsively-app/issues/883 needs some help too.

Please join us on discord if you have any questions on the implementation, and we can discuss: https://responsively.app/join-discord

**Comment by lyncasterc** [comment]
I saw that this doesn't seem to have been addressed yet so I went ahead and created a PR for it: #1081
