### ISSUE TITLE
Screen goes white once you enable a custom device

### ISSUE THREAD

**Issue by mmicheux** [responsively-org/responsively-app#932]
# 🐞 bug report

### ✍️ Description

When you add a custom device and enable it, the whole app goes to a white screen and a restart of the app is necessary to see the homepage again. 

### 🕵🏼‍♂️ Is this a regression?

I'm unsure, I just started using this app. 

### 🔬 Minimal Reproduction

1. Click to add a custom device, fill out the device info. 
2. Input a user agent string. The three user agents I have added are listed below. After adding each to my Schema(may not be what it's called on the app), I had to restart the app to view the devices again.
3. Click to save. 
4. Click checkbox to add to your schema. 
5. Screen goes white. 

#### User Agents:
- Firefox 10 on Mac OSX: Mozilla/5.0 (Macintosh; Intel Mac OS X x.y; rv:10.0) Gecko/20100101 Firefox/10.0 
- Chrome 87 on MacOs (Catalina): Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
- Chrome 113 on iOS 16.4 Apple iPhone: Mozilla/5.0 (iPhone; CPU iPhone OS 16_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/113.0.5672.109 Mobile/15E148 Safari/604.1 *(This one seems to have broken the app because when I quit and re-open, it is still a white screen.)* 

### 🌍 Your Environment

<pre><code>
*Cmd+F1 did nothing for me*

MacBook Pro
15-inch, 2018
Processor: 2.2 GHz 6-Core Intel Core i&
Graphics: Radeon Pro 555X 4 GB Intel UHD Graphics 630 1536MB
Memory: 16 GB 2400 MHz DDR4
Startup Disk: Macintosh HD
macOs: Ventura 13.2.1
</code></pre>

### 🔥 Exception or Error or Screenshot
<img width="1709" alt="Screenshot 2023-05-12 at 5 07 24 PM" src="https://github.com/responsively-org/responsively-app/assets/18272300/7a432814-7618-4018-8181-812ae802a22a">

**Comment by manojVivek** [comment]
Thanks for reporting this. Yes, I can confirm the app crashes when a new custom device is added. We have identified the issue and the fix will go in the next release(~in a week). 

The workaround until then is to close the app and reopen it and retry, as it only fails for the first time when the custom device is added and works fine after a restart.

**Comment by manojVivek** [comment]
Oh, I didn't check that scenario, I'll test this and get back.

**Comment by manojVivek** [comment]
Ok, it's not about the login or the user agent string. I found a bug in the delete workflow that is leaving some tangling device `ids` that is causing the crash. Pushed a fix to the PR should be good after this.

**Comment by manojVivek** [comment]
The fix is live on v1.3.0, please let me know if you still face the issue after the upgrade.
