### ISSUE TITLE
Add a link to website's sponsors page in the `ReleaseNotes` component

### ISSUE THREAD

**Issue by manojVivek** [responsively-org/responsively-app#940]
Link: https://responsively.app/sponsor/

Component link: https://github.com/responsively-org/responsively-app/blob/main/desktop-app/src/renderer/components/ReleaseNotes/index.tsx

Add a `Sponsor` button at the bottom of the Release Notes pop-up.

**Comment by liudi4046** [comment]
I can work on this issue. You can assign this to me :)

**Comment by manojVivek** [comment]
Great, please let me know if you have any questions. Please join our Discord for any discussions too: https://responsively.app/join-discord

**Comment by neelpatel1221** [comment]
hey liudi4046 do you need any help ?

**Comment by udaysai1311** [comment]
If the issue is not yet resolved I can work on it

**Comment by ANKITSINGH065** [comment]
what this means Release Notes pop-up. and can you explain where to add the support button? @manojVivek

**Comment by ReshadSadik** [comment]
Hi, @manojVivek . Assign it to me so I can make a pull request .
