### ISSUE TITLE
Include checksum file for the binaries in the release assets

### ISSUE THREAD

**Issue by kaushalyap** [responsively-org/responsively-app#95]
[latest-linux.yml](https://github.com/manojVivek/responsively-app/releases/download/v0.1.4/latest-linux.yml) contains the sha512 checksum of AppImage 0.1.3 instead of 0.1.4

By the way very useful project! thank you very much for your effort.

**Comment by manojVivek** [comment]
@kaushalyap will check it out and keep you posted. Thanks for reporting it.

**Comment by manojVivek** [comment]
I checked and `aEnJ5f+z/vwfxo+1G3TLOFFaqkk9rNiXesiAIQyN7lWad3OremY9VoIY1Ww6OSaAX9WflleT360DqvBFNzIuYw==` in the [latest-linux.yml](https://github.com/manojVivek/responsively-app/releases/download/v0.1.4/latest-linux.yml) file matches AppImage 0.1.4. 

AppImage 0.1.3's sha512 is `vFwc84G5YUVnv3hEQ5FS0x/9CMJvH4z9s0B5Qe5sflcMmHHtcWWeWak7HP6nLDLbPekhRoBWrS42chcx9euK6g==`

@kaushalyap Please let me know if I'm missing something.

**Comment by kaushalyap** [comment]
Did you updated the latest-linux.yml  of 0.1.4? As I remember when I viewing latest-linux.yml the url, path value was the file name of 0.1.4. and file that I have downloaded also 0.1.4. 

> aEnJ5f+z/vwfxo+1G3TLOFFaqkk9rNiXesiAIQyN7lWad3OremY9VoIY1Ww6OSaAX9WflleT360DqvBFNzIuYw== in the latest-linux.yml file matches AppImage 0.1.4.

Does not match with the file (0.1.4) I downloaded. Can you please download the AppImage 0.1.4 and check things locally. I remember in some other project also latest-linux.yml checksum not matching actual file. So I have seen some people release checksums files separately.

**Comment by manojVivek** [comment]
@kaushalyap It looks like the value in the `sha512` field is not the direct checksum of the downloaded file.

`electron-builder` makes use of https://github.com/develar/app-builder to build the binaries for distribution. And I tried generating the checksum for the downloaded v0.1.4 AppImage file using this tool and it outputs the same value as in the yml. 

```
$ ./app-builder blockmap -i /tmp/ResponsivelyApp-0.1.4.AppImage -o /tmp/throwaway.zip
{"size":109146691,"sha512":"aEnJ5f+z/vwfxo+1G3TLOFFaqkk9rNiXesiAIQyN7lWad3OremY9VoIY1Ww6OSaAX9WflleT360DqvBFNzIuYw=="}
```

You can check this issue for more details: https://github.com/electron-userland/electron-builder/issues/3913. I verified with the node script attached to this issue too. 

So I think we are good with this now. Please re-open it, if you still have concerns.

**Comment by kaushalyap** [comment]
@manojVivek 
It is annoying to download separate script for checking the checksum. Can you please provide me with the sha256sum of App-0.1.4.AppImage which can be generated locally by running
`sha512sum ResponsivelyApp-0.1.4.AppImage `

I am getting following
`6849c9e5ffb3fefc1fc68fb51b74cb38515aaa493dacd8977ac880210c8dee559a7773ab7a663d568218d56c3a3926805fd59f965793dfad03aaf04537322e63  ResponsivelyApp-0.1.4.AppImage`

Please consider releasing separate plain checksums with future releases.

**Comment by manojVivek** [comment]
Hey @kaushalyap, I get what you are saying. It will be good to have another file uploaded as `ResponsivelyApp-0.1.4.AppImage.sha512` with the plain checksum for the file. 

I'm re-opening this issue.

**Comment by jjavierdguezas** [comment]
Hey @manojVivek if we include a `package.json` script, lets say `yarn generate-checksums` that generates a checksum file for each file (`filename.extension.checksum.txt`) in the `release` folder (top level not subdirs) using [this code](https://github.com/electron-userland/electron-builder/issues/3913#issuecomment-504698845), would that help?

**Comment by manojVivek** [comment]
Yeah, that might help. 

But then it is not as simple as that, we will also need to have scripting to upload those files to the GitHub `release` as well. As I'm pretty sure `electron-builder` is not going to support this.

**Comment by jjavierdguezas** [comment]
@manojVivek oh I see I thought you upload the release files manually...

**Comment by manojVivek** [comment]
`electron-builder` uploads it all mandatory files automatically. 
I just manually upload one file `ResponsivelyApp-*.zip` which is needed for mac auto-updates and for some reason it is not taken care of by that package.

**Comment by jjavierdguezas** [comment]
> `electron-builder` uploads it all mandatory files automatically.
> I just manually upload one file `ResponsivelyApp-*.zip` which is needed for mac auto-updates and for some reason it is not taken care of by that package.

so if you upload a file manually, could you do the same with the checksum files until we found a better approach?

**Comment by jjavierdguezas** [comment]
Maybe this could help https://www.electron.build/configuration/configuration#afterallartifactbuild

**Comment by jjavierdguezas** [comment]
@manojVivek  that `.zip` file is generated in `release` folder when you package the app for mac?
Is it always `ResponsivelyApp-VERSION.zip` ?

**Comment by manojVivek** [comment]
I was checking the docs and I think that zip is not automatically getting emitted because we just have `dmg` under `targets` for `mac` in `package.json` file.

Changing that to `default` might help, as per the documentation: https://www.electron.build/configuration/mac

@jjavierdguezas  I'm trying that out now. Will keep you posted.

**Comment by jjavierdguezas** [comment]
ok @manojVivek I made a PR with some code that maybe you find useful, if not you can reject it...

**Comment by manojVivek** [comment]
@jjavierdguezas Thank you so much for implementing it. 

After making it to `default` it generated the `zip` file. But I'm not sure if that will work fine with the updater. I can validate it only during a release, shall I keep your PR open until the next release and then merge it?

**Comment by jjavierdguezas** [comment]
> @jjavierdguezas Thank you so much for implementing it.
> 
> After making it to `default` it generated the `zip` file. But I'm not sure if that will work fine with the updater. I can validate it only during a release, shall I keep your PR open until the next release and then merge it?

yes @manojVivek thats ok with me.
