### ISSUE TITLE
Extension Support

### ISSUE THREAD

**Issue by maclong9** [responsively-org/responsively-app#954]
# 🚀 Feature Request

### ✨ Describe the solution you'd like

First of all massive thank you for making an incredible application.

Feature: Is it possible to allow the ability to install chrome extensions? This would be useful for things like React Dev Tools.

**Comment by manojVivek** [comment]
Most common dev-tools extensions like react, vue, angular are already part of the app by default. You'll notice them in the devtools when you're an app using those technologies. 

Please let us know if you're looking for something else.
