### ISSUE TITLE
browser returns desktop resolution instead of mobile 

### ISSUE THREAD

**Issue by marcdakar** [responsively-org/responsively-app#955]
hi there, it seems that the browser window of  RESPONSIVELY Version: 1.3.0 does not report back that it is a MOBILE BROWSER, therefore the wrong "non-mobile" CSS files are loaded on my website.

Is there a solution for this, so that the suite does not return the parent browser window but the respective browser instances of the suite?

CHECK FOR YOURSELF:   http://demo.mobiledetect.net/

It would be helpful if we could fake the browser signature to make it respond as Mobile.

many greetings
marc

**Comment by emma2637** [comment]
Hello any update on this? it was working in a previous version of responsively app

**Comment by manojVivek** [comment]
This is fixed in the recent PR: https://github.com/responsively-org/responsively-app/pull/990

This will go live in the next release, probably by this weekend.
