### ISSUE TITLE
Device Manager and Layout left sidebar not showing on desktop app for Mac

### ISSUE THREAD

**Issue by alessiooli** [responsively-org/responsively-app#957]
Hey guys, I'm having a little bug on the Mac desktop App. 

# 🐞 bug report

### ✍️ Description

I can't seem to find any way to activate the left sidebar tab, it's not showing and I can't find any option in the menu to activate it. I can't add any new device.

### 🌍 Your Environment

Macbook Pro 15' 2016

### 🔥 Screenshot

![screenshot](https://github.com/responsively-org/responsively-app/assets/100276951/1bb1f170-015a-4cfe-9851-4897db04f649)

**Comment by FranLagorio** [comment]
It happens the same in my MacBook pro 16" 2023

**Comment by andresantos-tech** [comment]
The same happens in Ubuntu 20.04 (responsively-app version 1.6.0, using .AppImage)

**Comment by manojVivek** [comment]
That UI was from an older version of the app, we have updated it to the new format now. 

(Sorry, the videos on the website were outdated as well, but we have fixed them now to the new design). 

You can use this option to modify your devices:
<img width="760" alt="Screenshot 2023-07-31 at 10 07 10 AM" src="https://github.com/responsively-org/responsively-app/assets/1283424/e772d3cd-6498-49be-9fa6-cc4608f2c044">
