### ISSUE TITLE
Hide scrollbars on mobile

### ISSUE THREAD

**Issue by manojVivek** [responsively-org/responsively-app#963]
We need to hide the scrolls when the previewed device is a mobile to match the behaviour in real devices. Below are links to the issue and the PR that implemented this on the v0.x of the app, we need to replicate the same in the current version. 

Old issue: https://github.com/responsively-org/responsively-app/issues/255
Old PR: https://github.com/responsively-org/responsively-app/pull/351/files

**Comment by PeterKwesiAnsah** [comment]
@manojVivek  Please assign this issue to me

**Comment by manojVivek** [comment]
@PeterKwesiAnsah Go fot it!
