### ISSUE TITLE
bookmarks: Pass current page title to the create bookmark component automatically and autofil the bookmark name with it

### ISSUE THREAD

**Issue by manojVivek** [responsively-org/responsively-app#966]
> Can you check if it's easy to pass the title of the current page too so that it can be used in the `name` field as a default value?
> Please ignore if it requires more effort, we can convert this comment as an issue and deal with it in the future. 

_Originally posted by @manojVivek in https://github.com/responsively-org/responsively-app/pull/951#discussion_r1226755495_

**Comment by PeterKwesiAnsah** [comment]
@manojVivek Can you please assign this to me?

**Comment by manojVivek** [comment]
@PeterKwesiAnsah Go for it!
