### ISSUE TITLE
Switch to 100% zoom level when switching to the individual device layout

### ISSUE THREAD

**Issue by manojVivek** [responsively-org/responsively-app#970]
When switching to the individual layout using the following icon:

<img width="496" alt="Screenshot 2023-06-16 at 11 48 28 AM" src="https://github.com/responsively-org/responsively-app/assets/1283424/6e4bbf8a-2235-4c89-820c-1cfc079051f3">

Change the zoom level to `100%` and restore it back to the original zoom level when switching back to the non-individual layout. 

Ideally, we should use two different zoom levels in the redux store:
1. non-individual layout zoom (current one, no change needed)
2. one for individual layouts (This should be implemented)

**Comment by jibranabsarulislam** [comment]
on it! i just got it working on my end, I'll open a PR and tag this issue
