### ISSUE TITLE
Send per-device User-Agent / HTTP header

### ISSUE THREAD

**Issue by heatlai** [responsively-org/responsively-app#988]
# 🐞 bug report

### ✍️ Description

A specific user-agent string should be sent in the HTTP header upon request.
But the user-agent is all the same.

### 🕵🏼‍♂️ Is this a regression?

probably.

### 🔬 Minimal Reproduction

Please refer to the screenshot.

### 🌍 Your Environment

<pre><code>Apple M1 Pro - macOS 13.2
ResponsivelyApp v1.4.0
</code></pre>

### 🔥 Exception or Error or Screenshot

![image](https://github.com/responsively-org/responsively-app/assets/20237362/735481c6-e78b-4d86-b202-da93fd64f75a)

**Comment by manojVivek** [comment]
Thanks for reporting this, fixed in #990. 

It's a blunder that we missed this with the v1 rewrite. 🙇🏼
